// Code generated by protoc-gen-go. DO NOT EDIT.
// source: feder.proto

package federpb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	commonpb "github.com/milvus-io/milvus-proto/go-api/commonpb"
	schemapb "github.com/milvus-io/milvus-proto/go-api/schemapb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SegmentIndexData struct {
	SegmentID            int64         `protobuf:"varint,1,opt,name=segmentID,proto3" json:"segmentID,omitempty"`
	IndexData            string        `protobuf:"bytes,2,opt,name=index_data,json=indexData,proto3" json:"index_data,omitempty"`
	IdsSet               *schemapb.IDs `protobuf:"bytes,3,opt,name=ids_set,json=idsSet,proto3" json:"ids_set,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *SegmentIndexData) Reset()         { *m = SegmentIndexData{} }
func (m *SegmentIndexData) String() string { return proto.CompactTextString(m) }
func (*SegmentIndexData) ProtoMessage()    {}
func (*SegmentIndexData) Descriptor() ([]byte, []int) {
	return fileDescriptor_84d670fd126c7825, []int{0}
}

func (m *SegmentIndexData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SegmentIndexData.Unmarshal(m, b)
}
func (m *SegmentIndexData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SegmentIndexData.Marshal(b, m, deterministic)
}
func (m *SegmentIndexData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SegmentIndexData.Merge(m, src)
}
func (m *SegmentIndexData) XXX_Size() int {
	return xxx_messageInfo_SegmentIndexData.Size(m)
}
func (m *SegmentIndexData) XXX_DiscardUnknown() {
	xxx_messageInfo_SegmentIndexData.DiscardUnknown(m)
}

var xxx_messageInfo_SegmentIndexData proto.InternalMessageInfo

func (m *SegmentIndexData) GetSegmentID() int64 {
	if m != nil {
		return m.SegmentID
	}
	return 0
}

func (m *SegmentIndexData) GetIndexData() string {
	if m != nil {
		return m.IndexData
	}
	return ""
}

func (m *SegmentIndexData) GetIdsSet() *schemapb.IDs {
	if m != nil {
		return m.IdsSet
	}
	return nil
}

type ListIndexedSegmentRequest struct {
	Base                 *commonpb.MsgBase `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	CollectionName       string            `protobuf:"bytes,2,opt,name=collection_name,json=collectionName,proto3" json:"collection_name,omitempty"`
	IndexName            string            `protobuf:"bytes,3,opt,name=index_name,json=indexName,proto3" json:"index_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ListIndexedSegmentRequest) Reset()         { *m = ListIndexedSegmentRequest{} }
func (m *ListIndexedSegmentRequest) String() string { return proto.CompactTextString(m) }
func (*ListIndexedSegmentRequest) ProtoMessage()    {}
func (*ListIndexedSegmentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_84d670fd126c7825, []int{1}
}

func (m *ListIndexedSegmentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListIndexedSegmentRequest.Unmarshal(m, b)
}
func (m *ListIndexedSegmentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListIndexedSegmentRequest.Marshal(b, m, deterministic)
}
func (m *ListIndexedSegmentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListIndexedSegmentRequest.Merge(m, src)
}
func (m *ListIndexedSegmentRequest) XXX_Size() int {
	return xxx_messageInfo_ListIndexedSegmentRequest.Size(m)
}
func (m *ListIndexedSegmentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListIndexedSegmentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListIndexedSegmentRequest proto.InternalMessageInfo

func (m *ListIndexedSegmentRequest) GetBase() *commonpb.MsgBase {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *ListIndexedSegmentRequest) GetCollectionName() string {
	if m != nil {
		return m.CollectionName
	}
	return ""
}

func (m *ListIndexedSegmentRequest) GetIndexName() string {
	if m != nil {
		return m.IndexName
	}
	return ""
}

type ListIndexedSegmentResponse struct {
	Status               *commonpb.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	SegmentIDs           []int64          `protobuf:"varint,2,rep,packed,name=segmentIDs,proto3" json:"segmentIDs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ListIndexedSegmentResponse) Reset()         { *m = ListIndexedSegmentResponse{} }
func (m *ListIndexedSegmentResponse) String() string { return proto.CompactTextString(m) }
func (*ListIndexedSegmentResponse) ProtoMessage()    {}
func (*ListIndexedSegmentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_84d670fd126c7825, []int{2}
}

func (m *ListIndexedSegmentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListIndexedSegmentResponse.Unmarshal(m, b)
}
func (m *ListIndexedSegmentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListIndexedSegmentResponse.Marshal(b, m, deterministic)
}
func (m *ListIndexedSegmentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListIndexedSegmentResponse.Merge(m, src)
}
func (m *ListIndexedSegmentResponse) XXX_Size() int {
	return xxx_messageInfo_ListIndexedSegmentResponse.Size(m)
}
func (m *ListIndexedSegmentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListIndexedSegmentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListIndexedSegmentResponse proto.InternalMessageInfo

func (m *ListIndexedSegmentResponse) GetStatus() *commonpb.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ListIndexedSegmentResponse) GetSegmentIDs() []int64 {
	if m != nil {
		return m.SegmentIDs
	}
	return nil
}

type DescribeSegmentIndexDataRequest struct {
	Base                 *commonpb.MsgBase `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	CollectionName       string            `protobuf:"bytes,2,opt,name=collection_name,json=collectionName,proto3" json:"collection_name,omitempty"`
	IndexName            string            `protobuf:"bytes,3,opt,name=index_name,json=indexName,proto3" json:"index_name,omitempty"`
	SegmentsIDs          []int64           `protobuf:"varint,4,rep,packed,name=segmentsIDs,proto3" json:"segmentsIDs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *DescribeSegmentIndexDataRequest) Reset()         { *m = DescribeSegmentIndexDataRequest{} }
func (m *DescribeSegmentIndexDataRequest) String() string { return proto.CompactTextString(m) }
func (*DescribeSegmentIndexDataRequest) ProtoMessage()    {}
func (*DescribeSegmentIndexDataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_84d670fd126c7825, []int{3}
}

func (m *DescribeSegmentIndexDataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DescribeSegmentIndexDataRequest.Unmarshal(m, b)
}
func (m *DescribeSegmentIndexDataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DescribeSegmentIndexDataRequest.Marshal(b, m, deterministic)
}
func (m *DescribeSegmentIndexDataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DescribeSegmentIndexDataRequest.Merge(m, src)
}
func (m *DescribeSegmentIndexDataRequest) XXX_Size() int {
	return xxx_messageInfo_DescribeSegmentIndexDataRequest.Size(m)
}
func (m *DescribeSegmentIndexDataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DescribeSegmentIndexDataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DescribeSegmentIndexDataRequest proto.InternalMessageInfo

func (m *DescribeSegmentIndexDataRequest) GetBase() *commonpb.MsgBase {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *DescribeSegmentIndexDataRequest) GetCollectionName() string {
	if m != nil {
		return m.CollectionName
	}
	return ""
}

func (m *DescribeSegmentIndexDataRequest) GetIndexName() string {
	if m != nil {
		return m.IndexName
	}
	return ""
}

func (m *DescribeSegmentIndexDataRequest) GetSegmentsIDs() []int64 {
	if m != nil {
		return m.SegmentsIDs
	}
	return nil
}

type DescribeSegmentIndexDataResponse struct {
	Status *commonpb.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	// segmentID => segmentIndexData
	IndexData            map[int64]*SegmentIndexData `protobuf:"bytes,2,rep,name=index_data,json=indexData,proto3" json:"index_data,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	IndexParams          []*commonpb.KeyValuePair    `protobuf:"bytes,3,rep,name=index_params,json=indexParams,proto3" json:"index_params,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *DescribeSegmentIndexDataResponse) Reset()         { *m = DescribeSegmentIndexDataResponse{} }
func (m *DescribeSegmentIndexDataResponse) String() string { return proto.CompactTextString(m) }
func (*DescribeSegmentIndexDataResponse) ProtoMessage()    {}
func (*DescribeSegmentIndexDataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_84d670fd126c7825, []int{4}
}

func (m *DescribeSegmentIndexDataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DescribeSegmentIndexDataResponse.Unmarshal(m, b)
}
func (m *DescribeSegmentIndexDataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DescribeSegmentIndexDataResponse.Marshal(b, m, deterministic)
}
func (m *DescribeSegmentIndexDataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DescribeSegmentIndexDataResponse.Merge(m, src)
}
func (m *DescribeSegmentIndexDataResponse) XXX_Size() int {
	return xxx_messageInfo_DescribeSegmentIndexDataResponse.Size(m)
}
func (m *DescribeSegmentIndexDataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DescribeSegmentIndexDataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DescribeSegmentIndexDataResponse proto.InternalMessageInfo

func (m *DescribeSegmentIndexDataResponse) GetStatus() *commonpb.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *DescribeSegmentIndexDataResponse) GetIndexData() map[int64]*SegmentIndexData {
	if m != nil {
		return m.IndexData
	}
	return nil
}

func (m *DescribeSegmentIndexDataResponse) GetIndexParams() []*commonpb.KeyValuePair {
	if m != nil {
		return m.IndexParams
	}
	return nil
}

func init() {
	proto.RegisterType((*SegmentIndexData)(nil), "milvus.proto.feder.SegmentIndexData")
	proto.RegisterType((*ListIndexedSegmentRequest)(nil), "milvus.proto.feder.ListIndexedSegmentRequest")
	proto.RegisterType((*ListIndexedSegmentResponse)(nil), "milvus.proto.feder.ListIndexedSegmentResponse")
	proto.RegisterType((*DescribeSegmentIndexDataRequest)(nil), "milvus.proto.feder.DescribeSegmentIndexDataRequest")
	proto.RegisterType((*DescribeSegmentIndexDataResponse)(nil), "milvus.proto.feder.DescribeSegmentIndexDataResponse")
	proto.RegisterMapType((map[int64]*SegmentIndexData)(nil), "milvus.proto.feder.DescribeSegmentIndexDataResponse.IndexDataEntry")
}

func init() { proto.RegisterFile("feder.proto", fileDescriptor_84d670fd126c7825) }

var fileDescriptor_84d670fd126c7825 = []byte{
	// 460 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x93, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0xc7, 0xe5, 0xb8, 0x04, 0x65, 0x1c, 0x95, 0x6a, 0x4f, 0x26, 0x14, 0x30, 0x16, 0x12, 0xbe,
	0xd4, 0x29, 0xee, 0x05, 0xf5, 0x58, 0xcc, 0xa1, 0xe2, 0x43, 0x95, 0x23, 0x71, 0xe0, 0x12, 0xad,
	0xed, 0x21, 0x5d, 0x11, 0x7b, 0x5d, 0xcf, 0xba, 0x22, 0x57, 0xde, 0x81, 0xc7, 0xe1, 0x71, 0x78,
	0x0f, 0xe4, 0xf5, 0x92, 0x8f, 0xc6, 0x88, 0x03, 0x07, 0x6e, 0xde, 0xff, 0xce, 0x7f, 0xe6, 0x37,
	0xb3, 0x63, 0x70, 0x3e, 0x63, 0x8e, 0x75, 0x58, 0xd5, 0x52, 0x49, 0xc6, 0x0a, 0xb1, 0xbc, 0x6d,
	0xa8, 0x3b, 0x85, 0xfa, 0x66, 0x32, 0xce, 0x64, 0x51, 0xc8, 0xb2, 0xd3, 0x26, 0x63, 0xca, 0xae,
	0xb1, 0xe0, 0xdd, 0xc9, 0xff, 0x66, 0xc1, 0xd1, 0x0c, 0x17, 0x05, 0x96, 0xea, 0xb2, 0xcc, 0xf1,
	0x6b, 0xcc, 0x15, 0x67, 0xc7, 0x30, 0x22, 0xa3, 0xc5, 0xae, 0xe5, 0x59, 0x81, 0x9d, 0x6c, 0x04,
	0xf6, 0x18, 0x40, 0xb4, 0xa1, 0xf3, 0x9c, 0x2b, 0xee, 0x0e, 0x3c, 0x2b, 0x18, 0x25, 0x23, 0xb1,
	0x36, 0xbf, 0x84, 0xfb, 0x22, 0xa7, 0x39, 0xa1, 0x72, 0x6d, 0xcf, 0x0a, 0x9c, 0xc8, 0x0d, 0x77,
	0x98, 0x4c, 0xf9, 0xcb, 0x98, 0x92, 0xa1, 0xc8, 0x69, 0x86, 0xca, 0xff, 0x6e, 0xc1, 0xc3, 0x77,
	0x82, 0x3a, 0x02, 0xcc, 0x0d, 0x4f, 0x82, 0x37, 0x0d, 0x92, 0x62, 0xa7, 0x70, 0x90, 0x72, 0x42,
	0x0d, 0xe2, 0x44, 0xc7, 0xbb, 0xd9, 0x4c, 0x6b, 0xef, 0x69, 0x71, 0xc1, 0x09, 0x13, 0x1d, 0xc9,
	0x5e, 0xc0, 0x83, 0x4c, 0x2e, 0x97, 0x98, 0x29, 0x21, 0xcb, 0x79, 0xc9, 0x0b, 0x34, 0x98, 0x87,
	0x1b, 0xf9, 0x03, 0x2f, 0x70, 0xd3, 0x8a, 0x8e, 0xb1, 0xb7, 0x5a, 0x69, 0xaf, 0xfd, 0x1b, 0x98,
	0xf4, 0x61, 0x51, 0x25, 0x4b, 0x42, 0x76, 0x06, 0x43, 0x52, 0x5c, 0x35, 0x64, 0xc8, 0x1e, 0xf5,
	0x92, 0xcd, 0x74, 0x48, 0x62, 0x42, 0xd9, 0x13, 0x80, 0xf5, 0x24, 0xc9, 0x1d, 0x78, 0x76, 0x60,
	0x27, 0x5b, 0x8a, 0xff, 0xc3, 0x82, 0xa7, 0x31, 0x52, 0x56, 0x8b, 0x14, 0xef, 0xbe, 0xcb, 0x7f,
	0x1f, 0x08, 0xf3, 0xc0, 0x31, 0xac, 0xd4, 0xe2, 0x1f, 0x68, 0xfc, 0x6d, 0xc9, 0xff, 0x39, 0x00,
	0xef, 0xcf, 0xfc, 0xff, 0x32, 0xb9, 0xf4, 0xce, 0xda, 0xd9, 0x81, 0x13, 0xbd, 0x0e, 0xf7, 0xd7,
	0x3d, 0xfc, 0x5b, 0xf9, 0x70, 0xad, 0xbc, 0x29, 0x55, 0xbd, 0xda, 0xde, 0xdd, 0x18, 0xc6, 0x5d,
	0x8d, 0x8a, 0xd7, 0xbc, 0x20, 0xd7, 0xd6, 0x55, 0x9e, 0xf5, 0xe2, 0xbd, 0xc5, 0xd5, 0x47, 0xbe,
	0x6c, 0xf0, 0x8a, 0x8b, 0x3a, 0x71, 0xb4, 0xed, 0x4a, 0xbb, 0x26, 0x29, 0x1c, 0xee, 0x96, 0x60,
	0x47, 0x60, 0x7f, 0xc1, 0x95, 0xf9, 0x95, 0xda, 0x4f, 0x76, 0x0e, 0xf7, 0x6e, 0x5b, 0xb7, 0x7e,
	0x07, 0x27, 0x7a, 0xde, 0xd7, 0xc8, 0x5e, 0x03, 0x9d, 0xe5, 0x7c, 0xf0, 0xca, 0xba, 0x88, 0x3e,
	0x9d, 0x2e, 0x84, 0xba, 0x6e, 0xd2, 0x16, 0x67, 0xda, 0x99, 0x4f, 0x84, 0xfc, 0xfd, 0xa5, 0xd3,
	0x4c, 0x17, 0xf2, 0x84, 0x57, 0x62, 0xaa, 0xb3, 0x55, 0x69, 0x3a, 0xd4, 0xea, 0xd9, 0xaf, 0x00,
	0x00, 0x00, 0xff, 0xff, 0xbe, 0x27, 0xfe, 0x60, 0x31, 0x04, 0x00, 0x00,
}
