// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v3.21.4
// source: rg.proto

package rgpb

import (
	commonpb "github.com/milvus-io/milvus-proto/go-api/v2/commonpb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResourceGroupLimit struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeNum int32 `protobuf:"varint,1,opt,name=node_num,json=nodeNum,proto3" json:"node_num,omitempty"` // preserve for other limit.
}

func (x *ResourceGroupLimit) Reset() {
	*x = ResourceGroupLimit{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rg_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResourceGroupLimit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceGroupLimit) ProtoMessage() {}

func (x *ResourceGroupLimit) ProtoReflect() protoreflect.Message {
	mi := &file_rg_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceGroupLimit.ProtoReflect.Descriptor instead.
func (*ResourceGroupLimit) Descriptor() ([]byte, []int) {
	return file_rg_proto_rawDescGZIP(), []int{0}
}

func (x *ResourceGroupLimit) GetNodeNum() int32 {
	if x != nil {
		return x.NodeNum
	}
	return 0
}

type ResourceGroupTransfer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ResourceGroup string `protobuf:"bytes,1,opt,name=resource_group,json=resourceGroup,proto3" json:"resource_group,omitempty"` // resource groups can be transfered with current resource group.
}

func (x *ResourceGroupTransfer) Reset() {
	*x = ResourceGroupTransfer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rg_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResourceGroupTransfer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceGroupTransfer) ProtoMessage() {}

func (x *ResourceGroupTransfer) ProtoReflect() protoreflect.Message {
	mi := &file_rg_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceGroupTransfer.ProtoReflect.Descriptor instead.
func (*ResourceGroupTransfer) Descriptor() ([]byte, []int) {
	return file_rg_proto_rawDescGZIP(), []int{1}
}

func (x *ResourceGroupTransfer) GetResourceGroup() string {
	if x != nil {
		return x.ResourceGroup
	}
	return ""
}

type ResourceGroupNodeFilter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeLabels []*commonpb.KeyValuePair `protobuf:"bytes,1,rep,name=node_labels,json=nodeLabels,proto3" json:"node_labels,omitempty"` // node in resource group must match node labels requirements
}

func (x *ResourceGroupNodeFilter) Reset() {
	*x = ResourceGroupNodeFilter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rg_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResourceGroupNodeFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceGroupNodeFilter) ProtoMessage() {}

func (x *ResourceGroupNodeFilter) ProtoReflect() protoreflect.Message {
	mi := &file_rg_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceGroupNodeFilter.ProtoReflect.Descriptor instead.
func (*ResourceGroupNodeFilter) Descriptor() ([]byte, []int) {
	return file_rg_proto_rawDescGZIP(), []int{2}
}

func (x *ResourceGroupNodeFilter) GetNodeLabels() []*commonpb.KeyValuePair {
	if x != nil {
		return x.NodeLabels
	}
	return nil
}

type ResourceGroupConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Requests     *ResourceGroupLimit      `protobuf:"bytes,1,opt,name=requests,proto3" json:"requests,omitempty"`                             // requests node num in resource group, if node num is less than requests.nodeNum, it will be transfer from other resource group.
	Limits       *ResourceGroupLimit      `protobuf:"bytes,2,opt,name=limits,proto3" json:"limits,omitempty"`                                 // limited node num in resource group, if node num is more than limits.nodeNum, it will be transfer to other resource group.
	TransferFrom []*ResourceGroupTransfer `protobuf:"bytes,3,rep,name=transfer_from,json=transferFrom,proto3" json:"transfer_from,omitempty"` // missing node should be transfer from given resource group at high priority in repeated list.
	TransferTo   []*ResourceGroupTransfer `protobuf:"bytes,4,rep,name=transfer_to,json=transferTo,proto3" json:"transfer_to,omitempty"`       // redundant node should be transfer to given resource group at high priority in repeated list.
	NodeFilter   *ResourceGroupNodeFilter `protobuf:"bytes,5,opt,name=node_filter,json=nodeFilter,proto3" json:"node_filter,omitempty"`       // node in resource group must match node filters
}

func (x *ResourceGroupConfig) Reset() {
	*x = ResourceGroupConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rg_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResourceGroupConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceGroupConfig) ProtoMessage() {}

func (x *ResourceGroupConfig) ProtoReflect() protoreflect.Message {
	mi := &file_rg_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceGroupConfig.ProtoReflect.Descriptor instead.
func (*ResourceGroupConfig) Descriptor() ([]byte, []int) {
	return file_rg_proto_rawDescGZIP(), []int{3}
}

func (x *ResourceGroupConfig) GetRequests() *ResourceGroupLimit {
	if x != nil {
		return x.Requests
	}
	return nil
}

func (x *ResourceGroupConfig) GetLimits() *ResourceGroupLimit {
	if x != nil {
		return x.Limits
	}
	return nil
}

func (x *ResourceGroupConfig) GetTransferFrom() []*ResourceGroupTransfer {
	if x != nil {
		return x.TransferFrom
	}
	return nil
}

func (x *ResourceGroupConfig) GetTransferTo() []*ResourceGroupTransfer {
	if x != nil {
		return x.TransferTo
	}
	return nil
}

func (x *ResourceGroupConfig) GetNodeFilter() *ResourceGroupNodeFilter {
	if x != nil {
		return x.NodeFilter
	}
	return nil
}

var File_rg_proto protoreflect.FileDescriptor

var file_rg_proto_rawDesc = []byte{
	0x0a, 0x08, 0x72, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x6d, 0x69, 0x6c, 0x76,
	0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x72, 0x67, 0x1a, 0x0c, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2f, 0x0a, 0x12, 0x52, 0x65, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x12,
	0x19, 0x0a, 0x08, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x6e, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x07, 0x6e, 0x6f, 0x64, 0x65, 0x4e, 0x75, 0x6d, 0x22, 0x3e, 0x0a, 0x15, 0x52, 0x65,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x54, 0x72, 0x61, 0x6e, 0x73,
	0x66, 0x65, 0x72, 0x12, 0x25, 0x0a, 0x0e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f,
	0x67, 0x72, 0x6f, 0x75, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x72, 0x65, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x22, 0x5d, 0x0a, 0x17, 0x52, 0x65,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4e, 0x6f, 0x64, 0x65, 0x46,
	0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x42, 0x0a, 0x0b, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x6c, 0x61,
	0x62, 0x65, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x6d, 0x69, 0x6c,
	0x76, 0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x2e, 0x4b, 0x65, 0x79, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x50, 0x61, 0x69, 0x72, 0x52, 0x0a, 0x6e,
	0x6f, 0x64, 0x65, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x22, 0xf4, 0x02, 0x0a, 0x13, 0x52, 0x65,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x12, 0x3f, 0x0a, 0x08, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x6d, 0x69, 0x6c, 0x76, 0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x72, 0x67, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x47, 0x72,
	0x6f, 0x75, 0x70, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x52, 0x08, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x73, 0x12, 0x3b, 0x0a, 0x06, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x23, 0x2e, 0x6d, 0x69, 0x6c, 0x76, 0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x72, 0x67, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x47, 0x72, 0x6f,
	0x75, 0x70, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x52, 0x06, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x73, 0x12,
	0x4b, 0x0a, 0x0d, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x5f, 0x66, 0x72, 0x6f, 0x6d,
	0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x6d, 0x69, 0x6c, 0x76, 0x75, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x72, 0x67, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x52, 0x0c,
	0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x46, 0x72, 0x6f, 0x6d, 0x12, 0x47, 0x0a, 0x0b,
	0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x5f, 0x74, 0x6f, 0x18, 0x04, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x26, 0x2e, 0x6d, 0x69, 0x6c, 0x76, 0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x72, 0x67, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x47, 0x72, 0x6f, 0x75,
	0x70, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x52, 0x0a, 0x74, 0x72, 0x61, 0x6e, 0x73,
	0x66, 0x65, 0x72, 0x54, 0x6f, 0x12, 0x49, 0x0a, 0x0b, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x66, 0x69,
	0x6c, 0x74, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x6d, 0x69, 0x6c,
	0x76, 0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x72, 0x67, 0x2e, 0x52, 0x65, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4e, 0x6f, 0x64, 0x65, 0x46, 0x69,
	0x6c, 0x74, 0x65, 0x72, 0x52, 0x0a, 0x6e, 0x6f, 0x64, 0x65, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72,
	0x42, 0x70, 0x0a, 0x0e, 0x69, 0x6f, 0x2e, 0x6d, 0x69, 0x6c, 0x76, 0x75, 0x73, 0x2e, 0x67, 0x72,
	0x70, 0x63, 0x42, 0x12, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x47, 0x72, 0x6f, 0x75,
	0x70, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x30, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x69, 0x6c, 0x76, 0x75, 0x73, 0x2d, 0x69, 0x6f, 0x2f, 0x6d,
	0x69, 0x6c, 0x76, 0x75, 0x73, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x6f, 0x2d, 0x61,
	0x70, 0x69, 0x2f, 0x76, 0x32, 0x2f, 0x72, 0x67, 0x70, 0x62, 0xa0, 0x01, 0x01, 0xaa, 0x02, 0x12,
	0x4d, 0x69, 0x6c, 0x76, 0x75, 0x73, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x47, 0x72,
	0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rg_proto_rawDescOnce sync.Once
	file_rg_proto_rawDescData = file_rg_proto_rawDesc
)

func file_rg_proto_rawDescGZIP() []byte {
	file_rg_proto_rawDescOnce.Do(func() {
		file_rg_proto_rawDescData = protoimpl.X.CompressGZIP(file_rg_proto_rawDescData)
	})
	return file_rg_proto_rawDescData
}

var file_rg_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_rg_proto_goTypes = []interface{}{
	(*ResourceGroupLimit)(nil),      // 0: milvus.proto.rg.ResourceGroupLimit
	(*ResourceGroupTransfer)(nil),   // 1: milvus.proto.rg.ResourceGroupTransfer
	(*ResourceGroupNodeFilter)(nil), // 2: milvus.proto.rg.ResourceGroupNodeFilter
	(*ResourceGroupConfig)(nil),     // 3: milvus.proto.rg.ResourceGroupConfig
	(*commonpb.KeyValuePair)(nil),   // 4: milvus.proto.common.KeyValuePair
}
var file_rg_proto_depIdxs = []int32{
	4, // 0: milvus.proto.rg.ResourceGroupNodeFilter.node_labels:type_name -> milvus.proto.common.KeyValuePair
	0, // 1: milvus.proto.rg.ResourceGroupConfig.requests:type_name -> milvus.proto.rg.ResourceGroupLimit
	0, // 2: milvus.proto.rg.ResourceGroupConfig.limits:type_name -> milvus.proto.rg.ResourceGroupLimit
	1, // 3: milvus.proto.rg.ResourceGroupConfig.transfer_from:type_name -> milvus.proto.rg.ResourceGroupTransfer
	1, // 4: milvus.proto.rg.ResourceGroupConfig.transfer_to:type_name -> milvus.proto.rg.ResourceGroupTransfer
	2, // 5: milvus.proto.rg.ResourceGroupConfig.node_filter:type_name -> milvus.proto.rg.ResourceGroupNodeFilter
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_rg_proto_init() }
func file_rg_proto_init() {
	if File_rg_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rg_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResourceGroupLimit); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rg_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResourceGroupTransfer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rg_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResourceGroupNodeFilter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rg_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResourceGroupConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rg_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rg_proto_goTypes,
		DependencyIndexes: file_rg_proto_depIdxs,
		MessageInfos:      file_rg_proto_msgTypes,
	}.Build()
	File_rg_proto = out.File
	file_rg_proto_rawDesc = nil
	file_rg_proto_goTypes = nil
	file_rg_proto_depIdxs = nil
}
