// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rg.proto

package rgpb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ResourceGroupLimit struct {
	NodeNum              int32    `protobuf:"varint,1,opt,name=node_num,json=nodeNum,proto3" json:"node_num,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResourceGroupLimit) Reset()         { *m = ResourceGroupLimit{} }
func (m *ResourceGroupLimit) String() string { return proto.CompactTextString(m) }
func (*ResourceGroupLimit) ProtoMessage()    {}
func (*ResourceGroupLimit) Descriptor() ([]byte, []int) {
	return fileDescriptor_103cbf007c63c19b, []int{0}
}

func (m *ResourceGroupLimit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResourceGroupLimit.Unmarshal(m, b)
}
func (m *ResourceGroupLimit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResourceGroupLimit.Marshal(b, m, deterministic)
}
func (m *ResourceGroupLimit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResourceGroupLimit.Merge(m, src)
}
func (m *ResourceGroupLimit) XXX_Size() int {
	return xxx_messageInfo_ResourceGroupLimit.Size(m)
}
func (m *ResourceGroupLimit) XXX_DiscardUnknown() {
	xxx_messageInfo_ResourceGroupLimit.DiscardUnknown(m)
}

var xxx_messageInfo_ResourceGroupLimit proto.InternalMessageInfo

func (m *ResourceGroupLimit) GetNodeNum() int32 {
	if m != nil {
		return m.NodeNum
	}
	return 0
}

type ResourceGroupTransfer struct {
	ResourceGroup        string   `protobuf:"bytes,1,opt,name=resource_group,json=resourceGroup,proto3" json:"resource_group,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResourceGroupTransfer) Reset()         { *m = ResourceGroupTransfer{} }
func (m *ResourceGroupTransfer) String() string { return proto.CompactTextString(m) }
func (*ResourceGroupTransfer) ProtoMessage()    {}
func (*ResourceGroupTransfer) Descriptor() ([]byte, []int) {
	return fileDescriptor_103cbf007c63c19b, []int{1}
}

func (m *ResourceGroupTransfer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResourceGroupTransfer.Unmarshal(m, b)
}
func (m *ResourceGroupTransfer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResourceGroupTransfer.Marshal(b, m, deterministic)
}
func (m *ResourceGroupTransfer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResourceGroupTransfer.Merge(m, src)
}
func (m *ResourceGroupTransfer) XXX_Size() int {
	return xxx_messageInfo_ResourceGroupTransfer.Size(m)
}
func (m *ResourceGroupTransfer) XXX_DiscardUnknown() {
	xxx_messageInfo_ResourceGroupTransfer.DiscardUnknown(m)
}

var xxx_messageInfo_ResourceGroupTransfer proto.InternalMessageInfo

func (m *ResourceGroupTransfer) GetResourceGroup() string {
	if m != nil {
		return m.ResourceGroup
	}
	return ""
}

type ResourceGroupConfig struct {
	Requests             *ResourceGroupLimit      `protobuf:"bytes,1,opt,name=requests,proto3" json:"requests,omitempty"`
	Limits               *ResourceGroupLimit      `protobuf:"bytes,2,opt,name=limits,proto3" json:"limits,omitempty"`
	TransferFrom         []*ResourceGroupTransfer `protobuf:"bytes,3,rep,name=transfer_from,json=transferFrom,proto3" json:"transfer_from,omitempty"`
	TransferTo           []*ResourceGroupTransfer `protobuf:"bytes,4,rep,name=transfer_to,json=transferTo,proto3" json:"transfer_to,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *ResourceGroupConfig) Reset()         { *m = ResourceGroupConfig{} }
func (m *ResourceGroupConfig) String() string { return proto.CompactTextString(m) }
func (*ResourceGroupConfig) ProtoMessage()    {}
func (*ResourceGroupConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_103cbf007c63c19b, []int{2}
}

func (m *ResourceGroupConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResourceGroupConfig.Unmarshal(m, b)
}
func (m *ResourceGroupConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResourceGroupConfig.Marshal(b, m, deterministic)
}
func (m *ResourceGroupConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResourceGroupConfig.Merge(m, src)
}
func (m *ResourceGroupConfig) XXX_Size() int {
	return xxx_messageInfo_ResourceGroupConfig.Size(m)
}
func (m *ResourceGroupConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_ResourceGroupConfig.DiscardUnknown(m)
}

var xxx_messageInfo_ResourceGroupConfig proto.InternalMessageInfo

func (m *ResourceGroupConfig) GetRequests() *ResourceGroupLimit {
	if m != nil {
		return m.Requests
	}
	return nil
}

func (m *ResourceGroupConfig) GetLimits() *ResourceGroupLimit {
	if m != nil {
		return m.Limits
	}
	return nil
}

func (m *ResourceGroupConfig) GetTransferFrom() []*ResourceGroupTransfer {
	if m != nil {
		return m.TransferFrom
	}
	return nil
}

func (m *ResourceGroupConfig) GetTransferTo() []*ResourceGroupTransfer {
	if m != nil {
		return m.TransferTo
	}
	return nil
}

func init() {
	proto.RegisterType((*ResourceGroupLimit)(nil), "milvus.proto.rg.ResourceGroupLimit")
	proto.RegisterType((*ResourceGroupTransfer)(nil), "milvus.proto.rg.ResourceGroupTransfer")
	proto.RegisterType((*ResourceGroupConfig)(nil), "milvus.proto.rg.ResourceGroupConfig")
}

func init() { proto.RegisterFile("rg.proto", fileDescriptor_103cbf007c63c19b) }

var fileDescriptor_103cbf007c63c19b = []byte{
	// 304 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x91, 0xcf, 0x4a, 0x03, 0x31,
	0x10, 0x87, 0xd9, 0x56, 0x6b, 0x9d, 0xda, 0x0a, 0x11, 0x61, 0xbd, 0x95, 0x8a, 0xd2, 0x4b, 0xb3,
	0x52, 0x8f, 0x82, 0x42, 0x0b, 0xf6, 0xe0, 0x1f, 0xca, 0xd2, 0x93, 0x97, 0xd2, 0xae, 0x69, 0x0c,
	0x34, 0x3b, 0x71, 0x92, 0xf4, 0x79, 0xbc, 0xea, 0x53, 0xca, 0x6e, 0xbb, 0xc5, 0x55, 0x10, 0xbd,
	0x65, 0x32, 0xbf, 0xef, 0xcb, 0x0c, 0x81, 0x3a, 0x49, 0x6e, 0x08, 0x1d, 0xb2, 0x43, 0xad, 0x96,
	0x2b, 0x6f, 0xd7, 0x15, 0x27, 0xd9, 0x89, 0x80, 0xc5, 0xc2, 0xa2, 0xa7, 0x44, 0x8c, 0x08, 0xbd,
	0xb9, 0x57, 0x5a, 0x39, 0x76, 0x02, 0xf5, 0x14, 0x9f, 0xc5, 0x34, 0xf5, 0x3a, 0x0c, 0xda, 0x41,
	0x77, 0x37, 0xde, 0xcb, 0xea, 0x47, 0xaf, 0x3b, 0xd7, 0x70, 0x5c, 0x02, 0x26, 0x34, 0x4b, 0xed,
	0x42, 0x10, 0x3b, 0x83, 0x16, 0x6d, 0x1a, 0x53, 0x99, 0x75, 0x72, 0x72, 0x3f, 0x6e, 0xd2, 0xd7,
	0x78, 0xe7, 0xbd, 0x02, 0x47, 0x25, 0xc1, 0x10, 0xd3, 0x85, 0x92, 0xec, 0x06, 0xea, 0x24, 0x5e,
	0xbd, 0xb0, 0xce, 0xe6, 0x60, 0xa3, 0x7f, 0xca, 0xbf, 0x0d, 0xcb, 0x7f, 0x4e, 0x1a, 0x6f, 0x21,
	0x76, 0x05, 0xb5, 0x65, 0x76, 0x65, 0xc3, 0xca, 0xdf, 0xf1, 0x0d, 0xc2, 0xee, 0xa0, 0xe9, 0x36,
	0x8b, 0x4c, 0x17, 0x84, 0x3a, 0xac, 0xb6, 0xab, 0xdd, 0x46, 0xff, 0xfc, 0x77, 0x47, 0xb1, 0x7b,
	0x7c, 0x50, 0xc0, 0xb7, 0x84, 0x9a, 0x8d, 0xa0, 0xb1, 0x95, 0x39, 0x0c, 0x77, 0xfe, 0xa5, 0x82,
	0x02, 0x9d, 0xe0, 0xc0, 0x40, 0x4b, 0x61, 0xc1, 0x49, 0x32, 0xc9, 0xa0, 0xfc, 0x59, 0xe3, 0x4c,
	0x35, 0x0e, 0x9e, 0x2e, 0xa4, 0x72, 0x2f, 0x7e, 0xce, 0x13, 0xd4, 0xd1, 0x3a, 0xdd, 0x53, 0x58,
	0x9c, 0xf2, 0xf7, 0x22, 0x89, 0xbd, 0x99, 0x51, 0xd1, 0xaa, 0x1f, 0x91, 0x34, 0xf3, 0xb7, 0x20,
	0xf8, 0xa8, 0xb0, 0x87, 0xb5, 0x78, 0xb8, 0x54, 0x22, 0x75, 0x7c, 0x44, 0x26, 0x99, 0xd7, 0xf2,
	0xf4, 0xe5, 0x67, 0x00, 0x00, 0x00, 0xff, 0xff, 0xfc, 0x36, 0xfd, 0xaa, 0x32, 0x02, 0x00, 0x00,
}
