// Code generated by protoc-gen-go. DO NOT EDIT.
// source: msg.proto

package msgpb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	commonpb "github.com/milvus-io/milvus-proto/go-api/commonpb"
	schemapb "github.com/milvus-io/milvus-proto/go-api/schemapb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type InsertDataVersion int32

const (
	// 0 must refer to row-based format, since it's the first version in Milvus.
	InsertDataVersion_RowBased    InsertDataVersion = 0
	InsertDataVersion_ColumnBased InsertDataVersion = 1
)

var InsertDataVersion_name = map[int32]string{
	0: "RowBased",
	1: "ColumnBased",
}

var InsertDataVersion_value = map[string]int32{
	"RowBased":    0,
	"ColumnBased": 1,
}

func (x InsertDataVersion) String() string {
	return proto.EnumName(InsertDataVersion_name, int32(x))
}

func (InsertDataVersion) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{0}
}

type InsertRequest struct {
	Base           *commonpb.MsgBase `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	ShardName      string            `protobuf:"bytes,2,opt,name=shardName,proto3" json:"shardName,omitempty"`
	DbName         string            `protobuf:"bytes,3,opt,name=db_name,json=dbName,proto3" json:"db_name,omitempty"`
	CollectionName string            `protobuf:"bytes,4,opt,name=collection_name,json=collectionName,proto3" json:"collection_name,omitempty"`
	PartitionName  string            `protobuf:"bytes,5,opt,name=partition_name,json=partitionName,proto3" json:"partition_name,omitempty"`
	DbID           int64             `protobuf:"varint,6,opt,name=dbID,proto3" json:"dbID,omitempty"`
	CollectionID   int64             `protobuf:"varint,7,opt,name=collectionID,proto3" json:"collectionID,omitempty"`
	PartitionID    int64             `protobuf:"varint,8,opt,name=partitionID,proto3" json:"partitionID,omitempty"`
	SegmentID      int64             `protobuf:"varint,9,opt,name=segmentID,proto3" json:"segmentID,omitempty"`
	Timestamps     []uint64          `protobuf:"varint,10,rep,packed,name=timestamps,proto3" json:"timestamps,omitempty"`
	RowIDs         []int64           `protobuf:"varint,11,rep,packed,name=rowIDs,proto3" json:"rowIDs,omitempty"`
	// row_data was reserved for compatibility
	RowData              []*commonpb.Blob      `protobuf:"bytes,12,rep,name=row_data,json=rowData,proto3" json:"row_data,omitempty"`
	FieldsData           []*schemapb.FieldData `protobuf:"bytes,13,rep,name=fields_data,json=fieldsData,proto3" json:"fields_data,omitempty"`
	NumRows              uint64                `protobuf:"varint,14,opt,name=num_rows,json=numRows,proto3" json:"num_rows,omitempty"`
	Version              InsertDataVersion     `protobuf:"varint,15,opt,name=version,proto3,enum=milvus.proto.msg.InsertDataVersion" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *InsertRequest) Reset()         { *m = InsertRequest{} }
func (m *InsertRequest) String() string { return proto.CompactTextString(m) }
func (*InsertRequest) ProtoMessage()    {}
func (*InsertRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{0}
}

func (m *InsertRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InsertRequest.Unmarshal(m, b)
}
func (m *InsertRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InsertRequest.Marshal(b, m, deterministic)
}
func (m *InsertRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InsertRequest.Merge(m, src)
}
func (m *InsertRequest) XXX_Size() int {
	return xxx_messageInfo_InsertRequest.Size(m)
}
func (m *InsertRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InsertRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InsertRequest proto.InternalMessageInfo

func (m *InsertRequest) GetBase() *commonpb.MsgBase {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *InsertRequest) GetShardName() string {
	if m != nil {
		return m.ShardName
	}
	return ""
}

func (m *InsertRequest) GetDbName() string {
	if m != nil {
		return m.DbName
	}
	return ""
}

func (m *InsertRequest) GetCollectionName() string {
	if m != nil {
		return m.CollectionName
	}
	return ""
}

func (m *InsertRequest) GetPartitionName() string {
	if m != nil {
		return m.PartitionName
	}
	return ""
}

func (m *InsertRequest) GetDbID() int64 {
	if m != nil {
		return m.DbID
	}
	return 0
}

func (m *InsertRequest) GetCollectionID() int64 {
	if m != nil {
		return m.CollectionID
	}
	return 0
}

func (m *InsertRequest) GetPartitionID() int64 {
	if m != nil {
		return m.PartitionID
	}
	return 0
}

func (m *InsertRequest) GetSegmentID() int64 {
	if m != nil {
		return m.SegmentID
	}
	return 0
}

func (m *InsertRequest) GetTimestamps() []uint64 {
	if m != nil {
		return m.Timestamps
	}
	return nil
}

func (m *InsertRequest) GetRowIDs() []int64 {
	if m != nil {
		return m.RowIDs
	}
	return nil
}

func (m *InsertRequest) GetRowData() []*commonpb.Blob {
	if m != nil {
		return m.RowData
	}
	return nil
}

func (m *InsertRequest) GetFieldsData() []*schemapb.FieldData {
	if m != nil {
		return m.FieldsData
	}
	return nil
}

func (m *InsertRequest) GetNumRows() uint64 {
	if m != nil {
		return m.NumRows
	}
	return 0
}

func (m *InsertRequest) GetVersion() InsertDataVersion {
	if m != nil {
		return m.Version
	}
	return InsertDataVersion_RowBased
}

type DeleteRequest struct {
	Base                 *commonpb.MsgBase `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	ShardName            string            `protobuf:"bytes,2,opt,name=shardName,proto3" json:"shardName,omitempty"`
	DbName               string            `protobuf:"bytes,3,opt,name=db_name,json=dbName,proto3" json:"db_name,omitempty"`
	CollectionName       string            `protobuf:"bytes,4,opt,name=collection_name,json=collectionName,proto3" json:"collection_name,omitempty"`
	PartitionName        string            `protobuf:"bytes,5,opt,name=partition_name,json=partitionName,proto3" json:"partition_name,omitempty"`
	DbID                 int64             `protobuf:"varint,6,opt,name=dbID,proto3" json:"dbID,omitempty"`
	CollectionID         int64             `protobuf:"varint,7,opt,name=collectionID,proto3" json:"collectionID,omitempty"`
	PartitionID          int64             `protobuf:"varint,8,opt,name=partitionID,proto3" json:"partitionID,omitempty"`
	Int64PrimaryKeys     []int64           `protobuf:"varint,9,rep,packed,name=int64_primary_keys,json=int64PrimaryKeys,proto3" json:"int64_primary_keys,omitempty"`
	Timestamps           []uint64          `protobuf:"varint,10,rep,packed,name=timestamps,proto3" json:"timestamps,omitempty"`
	NumRows              int64             `protobuf:"varint,11,opt,name=num_rows,json=numRows,proto3" json:"num_rows,omitempty"`
	PrimaryKeys          *schemapb.IDs     `protobuf:"bytes,12,opt,name=primary_keys,json=primaryKeys,proto3" json:"primary_keys,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{1}
}

func (m *DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequest.Unmarshal(m, b)
}
func (m *DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequest.Merge(m, src)
}
func (m *DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRequest.Size(m)
}
func (m *DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequest proto.InternalMessageInfo

func (m *DeleteRequest) GetBase() *commonpb.MsgBase {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *DeleteRequest) GetShardName() string {
	if m != nil {
		return m.ShardName
	}
	return ""
}

func (m *DeleteRequest) GetDbName() string {
	if m != nil {
		return m.DbName
	}
	return ""
}

func (m *DeleteRequest) GetCollectionName() string {
	if m != nil {
		return m.CollectionName
	}
	return ""
}

func (m *DeleteRequest) GetPartitionName() string {
	if m != nil {
		return m.PartitionName
	}
	return ""
}

func (m *DeleteRequest) GetDbID() int64 {
	if m != nil {
		return m.DbID
	}
	return 0
}

func (m *DeleteRequest) GetCollectionID() int64 {
	if m != nil {
		return m.CollectionID
	}
	return 0
}

func (m *DeleteRequest) GetPartitionID() int64 {
	if m != nil {
		return m.PartitionID
	}
	return 0
}

func (m *DeleteRequest) GetInt64PrimaryKeys() []int64 {
	if m != nil {
		return m.Int64PrimaryKeys
	}
	return nil
}

func (m *DeleteRequest) GetTimestamps() []uint64 {
	if m != nil {
		return m.Timestamps
	}
	return nil
}

func (m *DeleteRequest) GetNumRows() int64 {
	if m != nil {
		return m.NumRows
	}
	return 0
}

func (m *DeleteRequest) GetPrimaryKeys() *schemapb.IDs {
	if m != nil {
		return m.PrimaryKeys
	}
	return nil
}

type MsgPosition struct {
	ChannelName          string   `protobuf:"bytes,1,opt,name=channel_name,json=channelName,proto3" json:"channel_name,omitempty"`
	MsgID                []byte   `protobuf:"bytes,2,opt,name=msgID,proto3" json:"msgID,omitempty"`
	MsgGroup             string   `protobuf:"bytes,3,opt,name=msgGroup,proto3" json:"msgGroup,omitempty"`
	Timestamp            uint64   `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgPosition) Reset()         { *m = MsgPosition{} }
func (m *MsgPosition) String() string { return proto.CompactTextString(m) }
func (*MsgPosition) ProtoMessage()    {}
func (*MsgPosition) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{2}
}

func (m *MsgPosition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgPosition.Unmarshal(m, b)
}
func (m *MsgPosition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgPosition.Marshal(b, m, deterministic)
}
func (m *MsgPosition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgPosition.Merge(m, src)
}
func (m *MsgPosition) XXX_Size() int {
	return xxx_messageInfo_MsgPosition.Size(m)
}
func (m *MsgPosition) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgPosition.DiscardUnknown(m)
}

var xxx_messageInfo_MsgPosition proto.InternalMessageInfo

func (m *MsgPosition) GetChannelName() string {
	if m != nil {
		return m.ChannelName
	}
	return ""
}

func (m *MsgPosition) GetMsgID() []byte {
	if m != nil {
		return m.MsgID
	}
	return nil
}

func (m *MsgPosition) GetMsgGroup() string {
	if m != nil {
		return m.MsgGroup
	}
	return ""
}

func (m *MsgPosition) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type CreateCollectionRequest struct {
	Base           *commonpb.MsgBase `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	DbName         string            `protobuf:"bytes,2,opt,name=db_name,json=dbName,proto3" json:"db_name,omitempty"`
	CollectionName string            `protobuf:"bytes,3,opt,name=collectionName,proto3" json:"collectionName,omitempty"`
	PartitionName  string            `protobuf:"bytes,4,opt,name=partitionName,proto3" json:"partitionName,omitempty"`
	// `schema` is the serialized `schema.CollectionSchema`
	DbID                 int64    `protobuf:"varint,5,opt,name=dbID,proto3" json:"dbID,omitempty"`
	CollectionID         int64    `protobuf:"varint,6,opt,name=collectionID,proto3" json:"collectionID,omitempty"`
	PartitionID          int64    `protobuf:"varint,7,opt,name=partitionID,proto3" json:"partitionID,omitempty"`
	Schema               []byte   `protobuf:"bytes,8,opt,name=schema,proto3" json:"schema,omitempty"`
	VirtualChannelNames  []string `protobuf:"bytes,9,rep,name=virtualChannelNames,proto3" json:"virtualChannelNames,omitempty"`
	PhysicalChannelNames []string `protobuf:"bytes,10,rep,name=physicalChannelNames,proto3" json:"physicalChannelNames,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateCollectionRequest) Reset()         { *m = CreateCollectionRequest{} }
func (m *CreateCollectionRequest) String() string { return proto.CompactTextString(m) }
func (*CreateCollectionRequest) ProtoMessage()    {}
func (*CreateCollectionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{3}
}

func (m *CreateCollectionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCollectionRequest.Unmarshal(m, b)
}
func (m *CreateCollectionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCollectionRequest.Marshal(b, m, deterministic)
}
func (m *CreateCollectionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCollectionRequest.Merge(m, src)
}
func (m *CreateCollectionRequest) XXX_Size() int {
	return xxx_messageInfo_CreateCollectionRequest.Size(m)
}
func (m *CreateCollectionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCollectionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCollectionRequest proto.InternalMessageInfo

func (m *CreateCollectionRequest) GetBase() *commonpb.MsgBase {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *CreateCollectionRequest) GetDbName() string {
	if m != nil {
		return m.DbName
	}
	return ""
}

func (m *CreateCollectionRequest) GetCollectionName() string {
	if m != nil {
		return m.CollectionName
	}
	return ""
}

func (m *CreateCollectionRequest) GetPartitionName() string {
	if m != nil {
		return m.PartitionName
	}
	return ""
}

func (m *CreateCollectionRequest) GetDbID() int64 {
	if m != nil {
		return m.DbID
	}
	return 0
}

func (m *CreateCollectionRequest) GetCollectionID() int64 {
	if m != nil {
		return m.CollectionID
	}
	return 0
}

func (m *CreateCollectionRequest) GetPartitionID() int64 {
	if m != nil {
		return m.PartitionID
	}
	return 0
}

func (m *CreateCollectionRequest) GetSchema() []byte {
	if m != nil {
		return m.Schema
	}
	return nil
}

func (m *CreateCollectionRequest) GetVirtualChannelNames() []string {
	if m != nil {
		return m.VirtualChannelNames
	}
	return nil
}

func (m *CreateCollectionRequest) GetPhysicalChannelNames() []string {
	if m != nil {
		return m.PhysicalChannelNames
	}
	return nil
}

type DropCollectionRequest struct {
	Base                 *commonpb.MsgBase `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	DbName               string            `protobuf:"bytes,2,opt,name=db_name,json=dbName,proto3" json:"db_name,omitempty"`
	CollectionName       string            `protobuf:"bytes,3,opt,name=collectionName,proto3" json:"collectionName,omitempty"`
	DbID                 int64             `protobuf:"varint,4,opt,name=dbID,proto3" json:"dbID,omitempty"`
	CollectionID         int64             `protobuf:"varint,5,opt,name=collectionID,proto3" json:"collectionID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *DropCollectionRequest) Reset()         { *m = DropCollectionRequest{} }
func (m *DropCollectionRequest) String() string { return proto.CompactTextString(m) }
func (*DropCollectionRequest) ProtoMessage()    {}
func (*DropCollectionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{4}
}

func (m *DropCollectionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DropCollectionRequest.Unmarshal(m, b)
}
func (m *DropCollectionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DropCollectionRequest.Marshal(b, m, deterministic)
}
func (m *DropCollectionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DropCollectionRequest.Merge(m, src)
}
func (m *DropCollectionRequest) XXX_Size() int {
	return xxx_messageInfo_DropCollectionRequest.Size(m)
}
func (m *DropCollectionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DropCollectionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DropCollectionRequest proto.InternalMessageInfo

func (m *DropCollectionRequest) GetBase() *commonpb.MsgBase {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *DropCollectionRequest) GetDbName() string {
	if m != nil {
		return m.DbName
	}
	return ""
}

func (m *DropCollectionRequest) GetCollectionName() string {
	if m != nil {
		return m.CollectionName
	}
	return ""
}

func (m *DropCollectionRequest) GetDbID() int64 {
	if m != nil {
		return m.DbID
	}
	return 0
}

func (m *DropCollectionRequest) GetCollectionID() int64 {
	if m != nil {
		return m.CollectionID
	}
	return 0
}

type CreatePartitionRequest struct {
	Base                 *commonpb.MsgBase `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	DbName               string            `protobuf:"bytes,2,opt,name=db_name,json=dbName,proto3" json:"db_name,omitempty"`
	CollectionName       string            `protobuf:"bytes,3,opt,name=collection_name,json=collectionName,proto3" json:"collection_name,omitempty"`
	PartitionName        string            `protobuf:"bytes,4,opt,name=partition_name,json=partitionName,proto3" json:"partition_name,omitempty"`
	DbID                 int64             `protobuf:"varint,5,opt,name=dbID,proto3" json:"dbID,omitempty"`
	CollectionID         int64             `protobuf:"varint,6,opt,name=collectionID,proto3" json:"collectionID,omitempty"`
	PartitionID          int64             `protobuf:"varint,7,opt,name=partitionID,proto3" json:"partitionID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *CreatePartitionRequest) Reset()         { *m = CreatePartitionRequest{} }
func (m *CreatePartitionRequest) String() string { return proto.CompactTextString(m) }
func (*CreatePartitionRequest) ProtoMessage()    {}
func (*CreatePartitionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{5}
}

func (m *CreatePartitionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePartitionRequest.Unmarshal(m, b)
}
func (m *CreatePartitionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePartitionRequest.Marshal(b, m, deterministic)
}
func (m *CreatePartitionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePartitionRequest.Merge(m, src)
}
func (m *CreatePartitionRequest) XXX_Size() int {
	return xxx_messageInfo_CreatePartitionRequest.Size(m)
}
func (m *CreatePartitionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePartitionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePartitionRequest proto.InternalMessageInfo

func (m *CreatePartitionRequest) GetBase() *commonpb.MsgBase {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *CreatePartitionRequest) GetDbName() string {
	if m != nil {
		return m.DbName
	}
	return ""
}

func (m *CreatePartitionRequest) GetCollectionName() string {
	if m != nil {
		return m.CollectionName
	}
	return ""
}

func (m *CreatePartitionRequest) GetPartitionName() string {
	if m != nil {
		return m.PartitionName
	}
	return ""
}

func (m *CreatePartitionRequest) GetDbID() int64 {
	if m != nil {
		return m.DbID
	}
	return 0
}

func (m *CreatePartitionRequest) GetCollectionID() int64 {
	if m != nil {
		return m.CollectionID
	}
	return 0
}

func (m *CreatePartitionRequest) GetPartitionID() int64 {
	if m != nil {
		return m.PartitionID
	}
	return 0
}

type DropPartitionRequest struct {
	Base                 *commonpb.MsgBase `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	DbName               string            `protobuf:"bytes,2,opt,name=db_name,json=dbName,proto3" json:"db_name,omitempty"`
	CollectionName       string            `protobuf:"bytes,3,opt,name=collection_name,json=collectionName,proto3" json:"collection_name,omitempty"`
	PartitionName        string            `protobuf:"bytes,4,opt,name=partition_name,json=partitionName,proto3" json:"partition_name,omitempty"`
	DbID                 int64             `protobuf:"varint,5,opt,name=dbID,proto3" json:"dbID,omitempty"`
	CollectionID         int64             `protobuf:"varint,6,opt,name=collectionID,proto3" json:"collectionID,omitempty"`
	PartitionID          int64             `protobuf:"varint,7,opt,name=partitionID,proto3" json:"partitionID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *DropPartitionRequest) Reset()         { *m = DropPartitionRequest{} }
func (m *DropPartitionRequest) String() string { return proto.CompactTextString(m) }
func (*DropPartitionRequest) ProtoMessage()    {}
func (*DropPartitionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{6}
}

func (m *DropPartitionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DropPartitionRequest.Unmarshal(m, b)
}
func (m *DropPartitionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DropPartitionRequest.Marshal(b, m, deterministic)
}
func (m *DropPartitionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DropPartitionRequest.Merge(m, src)
}
func (m *DropPartitionRequest) XXX_Size() int {
	return xxx_messageInfo_DropPartitionRequest.Size(m)
}
func (m *DropPartitionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DropPartitionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DropPartitionRequest proto.InternalMessageInfo

func (m *DropPartitionRequest) GetBase() *commonpb.MsgBase {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *DropPartitionRequest) GetDbName() string {
	if m != nil {
		return m.DbName
	}
	return ""
}

func (m *DropPartitionRequest) GetCollectionName() string {
	if m != nil {
		return m.CollectionName
	}
	return ""
}

func (m *DropPartitionRequest) GetPartitionName() string {
	if m != nil {
		return m.PartitionName
	}
	return ""
}

func (m *DropPartitionRequest) GetDbID() int64 {
	if m != nil {
		return m.DbID
	}
	return 0
}

func (m *DropPartitionRequest) GetCollectionID() int64 {
	if m != nil {
		return m.CollectionID
	}
	return 0
}

func (m *DropPartitionRequest) GetPartitionID() int64 {
	if m != nil {
		return m.PartitionID
	}
	return 0
}

type TimeTickMsg struct {
	Base                 *commonpb.MsgBase `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *TimeTickMsg) Reset()         { *m = TimeTickMsg{} }
func (m *TimeTickMsg) String() string { return proto.CompactTextString(m) }
func (*TimeTickMsg) ProtoMessage()    {}
func (*TimeTickMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{7}
}

func (m *TimeTickMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TimeTickMsg.Unmarshal(m, b)
}
func (m *TimeTickMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TimeTickMsg.Marshal(b, m, deterministic)
}
func (m *TimeTickMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TimeTickMsg.Merge(m, src)
}
func (m *TimeTickMsg) XXX_Size() int {
	return xxx_messageInfo_TimeTickMsg.Size(m)
}
func (m *TimeTickMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_TimeTickMsg.DiscardUnknown(m)
}

var xxx_messageInfo_TimeTickMsg proto.InternalMessageInfo

func (m *TimeTickMsg) GetBase() *commonpb.MsgBase {
	if m != nil {
		return m.Base
	}
	return nil
}

func init() {
	proto.RegisterEnum("milvus.proto.msg.InsertDataVersion", InsertDataVersion_name, InsertDataVersion_value)
	proto.RegisterType((*InsertRequest)(nil), "milvus.proto.msg.InsertRequest")
	proto.RegisterType((*DeleteRequest)(nil), "milvus.proto.msg.DeleteRequest")
	proto.RegisterType((*MsgPosition)(nil), "milvus.proto.msg.MsgPosition")
	proto.RegisterType((*CreateCollectionRequest)(nil), "milvus.proto.msg.CreateCollectionRequest")
	proto.RegisterType((*DropCollectionRequest)(nil), "milvus.proto.msg.DropCollectionRequest")
	proto.RegisterType((*CreatePartitionRequest)(nil), "milvus.proto.msg.CreatePartitionRequest")
	proto.RegisterType((*DropPartitionRequest)(nil), "milvus.proto.msg.DropPartitionRequest")
	proto.RegisterType((*TimeTickMsg)(nil), "milvus.proto.msg.TimeTickMsg")
}

func init() { proto.RegisterFile("msg.proto", fileDescriptor_c06e4cca6c2cc899) }

var fileDescriptor_c06e4cca6c2cc899 = []byte{
	// 760 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x55, 0x5d, 0x6f, 0xe3, 0x44,
	0x14, 0xc5, 0xb1, 0xf3, 0x75, 0xed, 0xa4, 0x65, 0x28, 0x5d, 0x6f, 0xb5, 0x5a, 0x19, 0xf3, 0x65,
	0x21, 0x36, 0xad, 0xc2, 0x8a, 0x17, 0x84, 0x56, 0x6a, 0x2c, 0x90, 0x85, 0x8a, 0xaa, 0xd1, 0x8a,
	0x07, 0x5e, 0xa2, 0x71, 0x32, 0x38, 0xd6, 0x7a, 0x3c, 0xc6, 0x63, 0x37, 0xca, 0x1b, 0xcf, 0x20,
	0xfe, 0x14, 0x4f, 0xf0, 0xaf, 0x90, 0x67, 0x9c, 0x38, 0x49, 0xd3, 0x16, 0x90, 0x40, 0x3c, 0xf4,
	0xcd, 0xf7, 0xdc, 0x73, 0xef, 0x78, 0xce, 0x39, 0xb2, 0xa1, 0xcf, 0x44, 0x34, 0xca, 0x72, 0x5e,
	0x70, 0x74, 0xcc, 0xe2, 0xe4, 0xa6, 0x14, 0xaa, 0x1a, 0x31, 0x11, 0x9d, 0x59, 0x33, 0xce, 0x18,
	0x4f, 0x15, 0x72, 0x66, 0x89, 0xd9, 0x82, 0x32, 0xa2, 0x2a, 0xf7, 0x0f, 0x03, 0x06, 0x41, 0x2a,
	0x68, 0x5e, 0x60, 0xfa, 0x63, 0x49, 0x45, 0x81, 0x2e, 0xc0, 0x08, 0x89, 0xa0, 0xb6, 0xe6, 0x68,
	0x9e, 0x39, 0x7e, 0x36, 0xda, 0x59, 0x57, 0x6f, 0xba, 0x12, 0xd1, 0x25, 0x11, 0x14, 0x4b, 0x26,
	0x7a, 0x06, 0x7d, 0xb1, 0x20, 0xf9, 0xfc, 0x5b, 0xc2, 0xa8, 0xdd, 0x72, 0x34, 0xaf, 0x8f, 0x1b,
	0x00, 0x3d, 0x81, 0xee, 0x3c, 0x9c, 0xa6, 0x55, 0x4f, 0x97, 0xbd, 0xce, 0x3c, 0x94, 0x8d, 0x8f,
	0xe1, 0x68, 0xc6, 0x93, 0x84, 0xce, 0x8a, 0x98, 0xa7, 0x8a, 0x60, 0x48, 0xc2, 0xb0, 0x81, 0x25,
	0xf1, 0x43, 0x18, 0x66, 0x24, 0x2f, 0xe2, 0x86, 0xd7, 0x96, 0xbc, 0xc1, 0x06, 0x95, 0x34, 0x04,
	0xc6, 0x3c, 0x0c, 0x7c, 0xbb, 0xe3, 0x68, 0x9e, 0x8e, 0xe5, 0x33, 0x72, 0xc1, 0x6a, 0x96, 0x05,
	0xbe, 0xdd, 0x95, 0xbd, 0x1d, 0x0c, 0x39, 0x60, 0x6e, 0x16, 0x05, 0xbe, 0xdd, 0x93, 0x94, 0x6d,
	0x48, 0x5e, 0x90, 0x46, 0x8c, 0xa6, 0x45, 0xe0, 0xdb, 0x7d, 0xd9, 0x6f, 0x00, 0xf4, 0x1c, 0xa0,
	0x88, 0x19, 0x15, 0x05, 0x61, 0x99, 0xb0, 0xc1, 0xd1, 0x3d, 0x03, 0x6f, 0x21, 0xe8, 0x14, 0x3a,
	0x39, 0x5f, 0x06, 0xbe, 0xb0, 0x4d, 0x47, 0xf7, 0x74, 0x5c, 0x57, 0xe8, 0x25, 0xf4, 0x72, 0xbe,
	0x9c, 0xce, 0x49, 0x41, 0x6c, 0xcb, 0xd1, 0x3d, 0x73, 0xfc, 0xf4, 0xa0, 0xd8, 0x97, 0x09, 0x0f,
	0x71, 0x37, 0xe7, 0x4b, 0x9f, 0x14, 0x04, 0xbd, 0x02, 0xf3, 0x87, 0x98, 0x26, 0x73, 0xa1, 0x06,
	0x07, 0x72, 0xf0, 0xf9, 0xee, 0x60, 0xed, 0xf0, 0x57, 0x15, 0xaf, 0x1a, 0xc2, 0xa0, 0x46, 0xe4,
	0x82, 0xa7, 0xd0, 0x4b, 0x4b, 0x36, 0xcd, 0xf9, 0x52, 0xd8, 0x43, 0x47, 0xf3, 0x0c, 0xdc, 0x4d,
	0x4b, 0x86, 0xf9, 0x52, 0xa0, 0x2f, 0xa1, 0x7b, 0x43, 0x73, 0x11, 0xf3, 0xd4, 0x3e, 0x72, 0x34,
	0x6f, 0x38, 0x7e, 0x7f, 0xb4, 0x1f, 0xa6, 0x91, 0x0a, 0x4b, 0xb5, 0xe9, 0x3b, 0x45, 0xc5, 0xeb,
	0x19, 0xf7, 0x77, 0x1d, 0x06, 0x3e, 0x4d, 0x68, 0x41, 0x1f, 0xb3, 0x74, 0x67, 0x96, 0x3e, 0x05,
	0x14, 0xa7, 0xc5, 0xe7, 0x2f, 0xa7, 0x59, 0x1e, 0x33, 0x92, 0xaf, 0xa6, 0x6f, 0xe8, 0x4a, 0xd8,
	0x7d, 0x99, 0x8c, 0x63, 0xd9, 0xb9, 0x56, 0x8d, 0x6f, 0xe8, 0x4a, 0x3c, 0x98, 0xad, 0x6d, 0x33,
	0x4d, 0x79, 0xd8, 0xc6, 0xcc, 0x2f, 0xc0, 0xda, 0x39, 0xc2, 0x92, 0x1e, 0xd8, 0x07, 0x93, 0x12,
	0xf8, 0x02, 0x9b, 0x59, 0x73, 0xae, 0xfb, 0x93, 0x06, 0xe6, 0x95, 0x88, 0xae, 0xb9, 0x90, 0xef,
	0x8d, 0xde, 0x03, 0x6b, 0xb6, 0x20, 0x69, 0x4a, 0x13, 0x25, 0x9a, 0x26, 0x45, 0x33, 0x6b, 0x4c,
	0x4a, 0x76, 0x02, 0x6d, 0x26, 0xa2, 0xc0, 0x97, 0xae, 0x59, 0x58, 0x15, 0xe8, 0x0c, 0x7a, 0x4c,
	0x44, 0x5f, 0xe7, 0xbc, 0xcc, 0x6a, 0xcb, 0x36, 0x75, 0xe5, 0xf5, 0xe6, 0x2a, 0xd2, 0x2e, 0x03,
	0x37, 0x80, 0xfb, 0xb3, 0x0e, 0x4f, 0x26, 0x39, 0x25, 0x05, 0x9d, 0x6c, 0x14, 0xfe, 0xe7, 0xb9,
	0xda, 0x4a, 0x4e, 0x6b, 0x27, 0x39, 0x1f, 0xc1, 0x5e, 0x44, 0xea, 0xd7, 0xdc, 0x0f, 0xce, 0x07,
	0xb0, 0x1b, 0x91, 0x3a, 0x5f, 0x77, 0xe4, 0xa6, 0x7d, 0x4f, 0x6e, 0x3a, 0x0f, 0xe7, 0xa6, 0x7b,
	0x3b, 0x37, 0xa7, 0xd0, 0x51, 0x66, 0xc9, 0x50, 0x59, 0xb8, 0xae, 0xd0, 0x05, 0xbc, 0x73, 0x13,
	0xe7, 0x45, 0x49, 0x92, 0x49, 0x63, 0x86, 0x0a, 0x54, 0x1f, 0x1f, 0x6a, 0xa1, 0x31, 0x9c, 0x64,
	0x8b, 0x95, 0x88, 0x67, 0x7b, 0x23, 0x20, 0x47, 0x0e, 0xf6, 0xdc, 0xdf, 0x34, 0x78, 0xd7, 0xcf,
	0x79, 0xf6, 0xbf, 0xb0, 0x62, 0x2d, 0xb2, 0x71, 0x8f, 0xc8, 0xed, 0xdb, 0x22, 0xbb, 0xbf, 0xb6,
	0xe0, 0x54, 0x25, 0xea, 0x7a, 0x2d, 0xec, 0xbf, 0x70, 0x8b, 0x03, 0x9f, 0x22, 0xfd, 0x2f, 0x7e,
	0x8a, 0xfe, 0xdb, 0x48, 0xb9, 0xbf, 0xb4, 0xe0, 0xa4, 0x32, 0xf5, 0x51, 0x8d, 0x4a, 0x8d, 0x57,
	0x60, 0xbe, 0x8e, 0x19, 0x7d, 0x1d, 0xcf, 0xde, 0x5c, 0x89, 0xe8, 0xef, 0x6b, 0xf0, 0xc9, 0x18,
	0xde, 0xbe, 0xf5, 0x73, 0x44, 0x16, 0xf4, 0x30, 0x5f, 0x56, 0xac, 0xf9, 0xf1, 0x5b, 0xe8, 0x08,
	0xcc, 0x09, 0x4f, 0x4a, 0x96, 0x2a, 0x40, 0xbb, 0xbc, 0xf8, 0x7e, 0x14, 0xc5, 0xc5, 0xa2, 0x0c,
	0xab, 0x95, 0xe7, 0xea, 0x8c, 0x17, 0x31, 0x5f, 0x3f, 0xc9, 0xd3, 0xce, 0x23, 0xfe, 0x82, 0x64,
	0xf1, 0x39, 0x13, 0x51, 0x16, 0x86, 0x1d, 0x89, 0x7d, 0xf6, 0x67, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x24, 0x14, 0x2e, 0x74, 0xf2, 0x09, 0x00, 0x00,
}
