// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common.proto

package commonpb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	descriptor "github.com/golang/protobuf/protoc-gen-go/descriptor"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Deprecated
type ErrorCode int32

const (
	ErrorCode_Success                       ErrorCode = 0
	ErrorCode_UnexpectedError               ErrorCode = 1
	ErrorCode_ConnectFailed                 ErrorCode = 2
	ErrorCode_PermissionDenied              ErrorCode = 3
	ErrorCode_CollectionNotExists           ErrorCode = 4
	ErrorCode_IllegalArgument               ErrorCode = 5
	ErrorCode_IllegalDimension              ErrorCode = 7
	ErrorCode_IllegalIndexType              ErrorCode = 8
	ErrorCode_IllegalCollectionName         ErrorCode = 9
	ErrorCode_IllegalTOPK                   ErrorCode = 10
	ErrorCode_IllegalRowRecord              ErrorCode = 11
	ErrorCode_IllegalVectorID               ErrorCode = 12
	ErrorCode_IllegalSearchResult           ErrorCode = 13
	ErrorCode_FileNotFound                  ErrorCode = 14
	ErrorCode_MetaFailed                    ErrorCode = 15
	ErrorCode_CacheFailed                   ErrorCode = 16
	ErrorCode_CannotCreateFolder            ErrorCode = 17
	ErrorCode_CannotCreateFile              ErrorCode = 18
	ErrorCode_CannotDeleteFolder            ErrorCode = 19
	ErrorCode_CannotDeleteFile              ErrorCode = 20
	ErrorCode_BuildIndexError               ErrorCode = 21
	ErrorCode_IllegalNLIST                  ErrorCode = 22
	ErrorCode_IllegalMetricType             ErrorCode = 23
	ErrorCode_OutOfMemory                   ErrorCode = 24
	ErrorCode_IndexNotExist                 ErrorCode = 25
	ErrorCode_EmptyCollection               ErrorCode = 26
	ErrorCode_UpdateImportTaskFailure       ErrorCode = 27
	ErrorCode_CollectionNameNotFound        ErrorCode = 28
	ErrorCode_CreateCredentialFailure       ErrorCode = 29
	ErrorCode_UpdateCredentialFailure       ErrorCode = 30
	ErrorCode_DeleteCredentialFailure       ErrorCode = 31
	ErrorCode_GetCredentialFailure          ErrorCode = 32
	ErrorCode_ListCredUsersFailure          ErrorCode = 33
	ErrorCode_GetUserFailure                ErrorCode = 34
	ErrorCode_CreateRoleFailure             ErrorCode = 35
	ErrorCode_DropRoleFailure               ErrorCode = 36
	ErrorCode_OperateUserRoleFailure        ErrorCode = 37
	ErrorCode_SelectRoleFailure             ErrorCode = 38
	ErrorCode_SelectUserFailure             ErrorCode = 39
	ErrorCode_SelectResourceFailure         ErrorCode = 40
	ErrorCode_OperatePrivilegeFailure       ErrorCode = 41
	ErrorCode_SelectGrantFailure            ErrorCode = 42
	ErrorCode_RefreshPolicyInfoCacheFailure ErrorCode = 43
	ErrorCode_ListPolicyFailure             ErrorCode = 44
	ErrorCode_NotShardLeader                ErrorCode = 45
	ErrorCode_NoReplicaAvailable            ErrorCode = 46
	ErrorCode_SegmentNotFound               ErrorCode = 47
	ErrorCode_ForceDeny                     ErrorCode = 48
	ErrorCode_RateLimit                     ErrorCode = 49
	ErrorCode_NodeIDNotMatch                ErrorCode = 50
	ErrorCode_UpsertAutoIDTrue              ErrorCode = 51
	ErrorCode_InsufficientMemoryToLoad      ErrorCode = 52
	ErrorCode_MemoryQuotaExhausted          ErrorCode = 53
	ErrorCode_DiskQuotaExhausted            ErrorCode = 54
	ErrorCode_TimeTickLongDelay             ErrorCode = 55
	ErrorCode_NotReadyServe                 ErrorCode = 56
	// Coord is switching from standby mode to active mode
	ErrorCode_NotReadyCoordActivating ErrorCode = 57
	// Service availability.
	// NA: Not Available.
	ErrorCode_DataCoordNA ErrorCode = 100
	// internal error code.
	ErrorCode_DDRequestRace ErrorCode = 1000
)

var ErrorCode_name = map[int32]string{
	0:    "Success",
	1:    "UnexpectedError",
	2:    "ConnectFailed",
	3:    "PermissionDenied",
	4:    "CollectionNotExists",
	5:    "IllegalArgument",
	7:    "IllegalDimension",
	8:    "IllegalIndexType",
	9:    "IllegalCollectionName",
	10:   "IllegalTOPK",
	11:   "IllegalRowRecord",
	12:   "IllegalVectorID",
	13:   "IllegalSearchResult",
	14:   "FileNotFound",
	15:   "MetaFailed",
	16:   "CacheFailed",
	17:   "CannotCreateFolder",
	18:   "CannotCreateFile",
	19:   "CannotDeleteFolder",
	20:   "CannotDeleteFile",
	21:   "BuildIndexError",
	22:   "IllegalNLIST",
	23:   "IllegalMetricType",
	24:   "OutOfMemory",
	25:   "IndexNotExist",
	26:   "EmptyCollection",
	27:   "UpdateImportTaskFailure",
	28:   "CollectionNameNotFound",
	29:   "CreateCredentialFailure",
	30:   "UpdateCredentialFailure",
	31:   "DeleteCredentialFailure",
	32:   "GetCredentialFailure",
	33:   "ListCredUsersFailure",
	34:   "GetUserFailure",
	35:   "CreateRoleFailure",
	36:   "DropRoleFailure",
	37:   "OperateUserRoleFailure",
	38:   "SelectRoleFailure",
	39:   "SelectUserFailure",
	40:   "SelectResourceFailure",
	41:   "OperatePrivilegeFailure",
	42:   "SelectGrantFailure",
	43:   "RefreshPolicyInfoCacheFailure",
	44:   "ListPolicyFailure",
	45:   "NotShardLeader",
	46:   "NoReplicaAvailable",
	47:   "SegmentNotFound",
	48:   "ForceDeny",
	49:   "RateLimit",
	50:   "NodeIDNotMatch",
	51:   "UpsertAutoIDTrue",
	52:   "InsufficientMemoryToLoad",
	53:   "MemoryQuotaExhausted",
	54:   "DiskQuotaExhausted",
	55:   "TimeTickLongDelay",
	56:   "NotReadyServe",
	57:   "NotReadyCoordActivating",
	100:  "DataCoordNA",
	1000: "DDRequestRace",
}

var ErrorCode_value = map[string]int32{
	"Success":                       0,
	"UnexpectedError":               1,
	"ConnectFailed":                 2,
	"PermissionDenied":              3,
	"CollectionNotExists":           4,
	"IllegalArgument":               5,
	"IllegalDimension":              7,
	"IllegalIndexType":              8,
	"IllegalCollectionName":         9,
	"IllegalTOPK":                   10,
	"IllegalRowRecord":              11,
	"IllegalVectorID":               12,
	"IllegalSearchResult":           13,
	"FileNotFound":                  14,
	"MetaFailed":                    15,
	"CacheFailed":                   16,
	"CannotCreateFolder":            17,
	"CannotCreateFile":              18,
	"CannotDeleteFolder":            19,
	"CannotDeleteFile":              20,
	"BuildIndexError":               21,
	"IllegalNLIST":                  22,
	"IllegalMetricType":             23,
	"OutOfMemory":                   24,
	"IndexNotExist":                 25,
	"EmptyCollection":               26,
	"UpdateImportTaskFailure":       27,
	"CollectionNameNotFound":        28,
	"CreateCredentialFailure":       29,
	"UpdateCredentialFailure":       30,
	"DeleteCredentialFailure":       31,
	"GetCredentialFailure":          32,
	"ListCredUsersFailure":          33,
	"GetUserFailure":                34,
	"CreateRoleFailure":             35,
	"DropRoleFailure":               36,
	"OperateUserRoleFailure":        37,
	"SelectRoleFailure":             38,
	"SelectUserFailure":             39,
	"SelectResourceFailure":         40,
	"OperatePrivilegeFailure":       41,
	"SelectGrantFailure":            42,
	"RefreshPolicyInfoCacheFailure": 43,
	"ListPolicyFailure":             44,
	"NotShardLeader":                45,
	"NoReplicaAvailable":            46,
	"SegmentNotFound":               47,
	"ForceDeny":                     48,
	"RateLimit":                     49,
	"NodeIDNotMatch":                50,
	"UpsertAutoIDTrue":              51,
	"InsufficientMemoryToLoad":      52,
	"MemoryQuotaExhausted":          53,
	"DiskQuotaExhausted":            54,
	"TimeTickLongDelay":             55,
	"NotReadyServe":                 56,
	"NotReadyCoordActivating":       57,
	"DataCoordNA":                   100,
	"DDRequestRace":                 1000,
}

func (x ErrorCode) String() string {
	return proto.EnumName(ErrorCode_name, int32(x))
}

func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{0}
}

type IndexState int32

const (
	IndexState_IndexStateNone IndexState = 0
	IndexState_Unissued       IndexState = 1
	IndexState_InProgress     IndexState = 2
	IndexState_Finished       IndexState = 3
	IndexState_Failed         IndexState = 4
	IndexState_Retry          IndexState = 5
)

var IndexState_name = map[int32]string{
	0: "IndexStateNone",
	1: "Unissued",
	2: "InProgress",
	3: "Finished",
	4: "Failed",
	5: "Retry",
}

var IndexState_value = map[string]int32{
	"IndexStateNone": 0,
	"Unissued":       1,
	"InProgress":     2,
	"Finished":       3,
	"Failed":         4,
	"Retry":          5,
}

func (x IndexState) String() string {
	return proto.EnumName(IndexState_name, int32(x))
}

func (IndexState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{1}
}

type SegmentState int32

const (
	SegmentState_SegmentStateNone SegmentState = 0
	SegmentState_NotExist         SegmentState = 1
	SegmentState_Growing          SegmentState = 2
	SegmentState_Sealed           SegmentState = 3
	SegmentState_Flushed          SegmentState = 4
	SegmentState_Flushing         SegmentState = 5
	SegmentState_Dropped          SegmentState = 6
	SegmentState_Importing        SegmentState = 7
)

var SegmentState_name = map[int32]string{
	0: "SegmentStateNone",
	1: "NotExist",
	2: "Growing",
	3: "Sealed",
	4: "Flushed",
	5: "Flushing",
	6: "Dropped",
	7: "Importing",
}

var SegmentState_value = map[string]int32{
	"SegmentStateNone": 0,
	"NotExist":         1,
	"Growing":          2,
	"Sealed":           3,
	"Flushed":          4,
	"Flushing":         5,
	"Dropped":          6,
	"Importing":        7,
}

func (x SegmentState) String() string {
	return proto.EnumName(SegmentState_name, int32(x))
}

func (SegmentState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{2}
}

type PlaceholderType int32

const (
	PlaceholderType_None          PlaceholderType = 0
	PlaceholderType_BinaryVector  PlaceholderType = 100
	PlaceholderType_FloatVector   PlaceholderType = 101
	PlaceholderType_Float16Vector PlaceholderType = 102
	PlaceholderType_Int64         PlaceholderType = 5
	PlaceholderType_VarChar       PlaceholderType = 21
)

var PlaceholderType_name = map[int32]string{
	0:   "None",
	100: "BinaryVector",
	101: "FloatVector",
	102: "Float16Vector",
	5:   "Int64",
	21:  "VarChar",
}

var PlaceholderType_value = map[string]int32{
	"None":          0,
	"BinaryVector":  100,
	"FloatVector":   101,
	"Float16Vector": 102,
	"Int64":         5,
	"VarChar":       21,
}

func (x PlaceholderType) String() string {
	return proto.EnumName(PlaceholderType_name, int32(x))
}

func (PlaceholderType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{3}
}

type MsgType int32

const (
	MsgType_Undefined MsgType = 0
	// DEFINITION REQUESTS: COLLECTION
	MsgType_CreateCollection   MsgType = 100
	MsgType_DropCollection     MsgType = 101
	MsgType_HasCollection      MsgType = 102
	MsgType_DescribeCollection MsgType = 103
	MsgType_ShowCollections    MsgType = 104
	MsgType_GetSystemConfigs   MsgType = 105
	MsgType_LoadCollection     MsgType = 106
	MsgType_ReleaseCollection  MsgType = 107
	MsgType_CreateAlias        MsgType = 108
	MsgType_DropAlias          MsgType = 109
	MsgType_AlterAlias         MsgType = 110
	MsgType_AlterCollection    MsgType = 111
	MsgType_RenameCollection   MsgType = 112
	MsgType_DescribeAlias      MsgType = 113
	MsgType_ListAliases        MsgType = 114
	// DEFINITION REQUESTS: PARTITION
	MsgType_CreatePartition   MsgType = 200
	MsgType_DropPartition     MsgType = 201
	MsgType_HasPartition      MsgType = 202
	MsgType_DescribePartition MsgType = 203
	MsgType_ShowPartitions    MsgType = 204
	MsgType_LoadPartitions    MsgType = 205
	MsgType_ReleasePartitions MsgType = 206
	// DEFINE REQUESTS: SEGMENT
	MsgType_ShowSegments                  MsgType = 250
	MsgType_DescribeSegment               MsgType = 251
	MsgType_LoadSegments                  MsgType = 252
	MsgType_ReleaseSegments               MsgType = 253
	MsgType_HandoffSegments               MsgType = 254
	MsgType_LoadBalanceSegments           MsgType = 255
	MsgType_DescribeSegments              MsgType = 256
	MsgType_FederListIndexedSegment       MsgType = 257
	MsgType_FederDescribeSegmentIndexData MsgType = 258
	// DEFINITION REQUESTS: INDEX
	MsgType_CreateIndex        MsgType = 300
	MsgType_DescribeIndex      MsgType = 301
	MsgType_DropIndex          MsgType = 302
	MsgType_GetIndexStatistics MsgType = 303
	// MANIPULATION REQUESTS
	MsgType_Insert             MsgType = 400
	MsgType_Delete             MsgType = 401
	MsgType_Flush              MsgType = 402
	MsgType_ResendSegmentStats MsgType = 403
	MsgType_Upsert             MsgType = 404
	// QUERY
	MsgType_Search                   MsgType = 500
	MsgType_SearchResult             MsgType = 501
	MsgType_GetIndexState            MsgType = 502
	MsgType_GetIndexBuildProgress    MsgType = 503
	MsgType_GetCollectionStatistics  MsgType = 504
	MsgType_GetPartitionStatistics   MsgType = 505
	MsgType_Retrieve                 MsgType = 506
	MsgType_RetrieveResult           MsgType = 507
	MsgType_WatchDmChannels          MsgType = 508
	MsgType_RemoveDmChannels         MsgType = 509
	MsgType_WatchQueryChannels       MsgType = 510
	MsgType_RemoveQueryChannels      MsgType = 511
	MsgType_SealedSegmentsChangeInfo MsgType = 512
	MsgType_WatchDeltaChannels       MsgType = 513
	MsgType_GetShardLeaders          MsgType = 514
	MsgType_GetReplicas              MsgType = 515
	MsgType_UnsubDmChannel           MsgType = 516
	MsgType_GetDistribution          MsgType = 517
	MsgType_SyncDistribution         MsgType = 518
	// DATA SERVICE
	MsgType_SegmentInfo     MsgType = 600
	MsgType_SystemInfo      MsgType = 601
	MsgType_GetRecoveryInfo MsgType = 602
	MsgType_GetSegmentState MsgType = 603
	// SYSTEM CONTROL
	MsgType_TimeTick          MsgType = 1200
	MsgType_QueryNodeStats    MsgType = 1201
	MsgType_LoadIndex         MsgType = 1202
	MsgType_RequestID         MsgType = 1203
	MsgType_RequestTSO        MsgType = 1204
	MsgType_AllocateSegment   MsgType = 1205
	MsgType_SegmentStatistics MsgType = 1206
	MsgType_SegmentFlushDone  MsgType = 1207
	MsgType_DataNodeTt        MsgType = 1208
	MsgType_Connect           MsgType = 1209
	MsgType_ListClientInfos   MsgType = 1210
	MsgType_AllocTimestamp    MsgType = 1211
	// Credential
	MsgType_CreateCredential  MsgType = 1500
	MsgType_GetCredential     MsgType = 1501
	MsgType_DeleteCredential  MsgType = 1502
	MsgType_UpdateCredential  MsgType = 1503
	MsgType_ListCredUsernames MsgType = 1504
	// RBAC
	MsgType_CreateRole             MsgType = 1600
	MsgType_DropRole               MsgType = 1601
	MsgType_OperateUserRole        MsgType = 1602
	MsgType_SelectRole             MsgType = 1603
	MsgType_SelectUser             MsgType = 1604
	MsgType_SelectResource         MsgType = 1605
	MsgType_OperatePrivilege       MsgType = 1606
	MsgType_SelectGrant            MsgType = 1607
	MsgType_RefreshPolicyInfoCache MsgType = 1608
	MsgType_ListPolicy             MsgType = 1609
	// Resource group
	MsgType_CreateResourceGroup   MsgType = 1700
	MsgType_DropResourceGroup     MsgType = 1701
	MsgType_ListResourceGroups    MsgType = 1702
	MsgType_DescribeResourceGroup MsgType = 1703
	MsgType_TransferNode          MsgType = 1704
	MsgType_TransferReplica       MsgType = 1705
	// Database group
	MsgType_CreateDatabase MsgType = 1801
	MsgType_DropDatabase   MsgType = 1802
	MsgType_ListDatabases  MsgType = 1803
)

var MsgType_name = map[int32]string{
	0:    "Undefined",
	100:  "CreateCollection",
	101:  "DropCollection",
	102:  "HasCollection",
	103:  "DescribeCollection",
	104:  "ShowCollections",
	105:  "GetSystemConfigs",
	106:  "LoadCollection",
	107:  "ReleaseCollection",
	108:  "CreateAlias",
	109:  "DropAlias",
	110:  "AlterAlias",
	111:  "AlterCollection",
	112:  "RenameCollection",
	113:  "DescribeAlias",
	114:  "ListAliases",
	200:  "CreatePartition",
	201:  "DropPartition",
	202:  "HasPartition",
	203:  "DescribePartition",
	204:  "ShowPartitions",
	205:  "LoadPartitions",
	206:  "ReleasePartitions",
	250:  "ShowSegments",
	251:  "DescribeSegment",
	252:  "LoadSegments",
	253:  "ReleaseSegments",
	254:  "HandoffSegments",
	255:  "LoadBalanceSegments",
	256:  "DescribeSegments",
	257:  "FederListIndexedSegment",
	258:  "FederDescribeSegmentIndexData",
	300:  "CreateIndex",
	301:  "DescribeIndex",
	302:  "DropIndex",
	303:  "GetIndexStatistics",
	400:  "Insert",
	401:  "Delete",
	402:  "Flush",
	403:  "ResendSegmentStats",
	404:  "Upsert",
	500:  "Search",
	501:  "SearchResult",
	502:  "GetIndexState",
	503:  "GetIndexBuildProgress",
	504:  "GetCollectionStatistics",
	505:  "GetPartitionStatistics",
	506:  "Retrieve",
	507:  "RetrieveResult",
	508:  "WatchDmChannels",
	509:  "RemoveDmChannels",
	510:  "WatchQueryChannels",
	511:  "RemoveQueryChannels",
	512:  "SealedSegmentsChangeInfo",
	513:  "WatchDeltaChannels",
	514:  "GetShardLeaders",
	515:  "GetReplicas",
	516:  "UnsubDmChannel",
	517:  "GetDistribution",
	518:  "SyncDistribution",
	600:  "SegmentInfo",
	601:  "SystemInfo",
	602:  "GetRecoveryInfo",
	603:  "GetSegmentState",
	1200: "TimeTick",
	1201: "QueryNodeStats",
	1202: "LoadIndex",
	1203: "RequestID",
	1204: "RequestTSO",
	1205: "AllocateSegment",
	1206: "SegmentStatistics",
	1207: "SegmentFlushDone",
	1208: "DataNodeTt",
	1209: "Connect",
	1210: "ListClientInfos",
	1211: "AllocTimestamp",
	1500: "CreateCredential",
	1501: "GetCredential",
	1502: "DeleteCredential",
	1503: "UpdateCredential",
	1504: "ListCredUsernames",
	1600: "CreateRole",
	1601: "DropRole",
	1602: "OperateUserRole",
	1603: "SelectRole",
	1604: "SelectUser",
	1605: "SelectResource",
	1606: "OperatePrivilege",
	1607: "SelectGrant",
	1608: "RefreshPolicyInfoCache",
	1609: "ListPolicy",
	1700: "CreateResourceGroup",
	1701: "DropResourceGroup",
	1702: "ListResourceGroups",
	1703: "DescribeResourceGroup",
	1704: "TransferNode",
	1705: "TransferReplica",
	1801: "CreateDatabase",
	1802: "DropDatabase",
	1803: "ListDatabases",
}

var MsgType_value = map[string]int32{
	"Undefined":                     0,
	"CreateCollection":              100,
	"DropCollection":                101,
	"HasCollection":                 102,
	"DescribeCollection":            103,
	"ShowCollections":               104,
	"GetSystemConfigs":              105,
	"LoadCollection":                106,
	"ReleaseCollection":             107,
	"CreateAlias":                   108,
	"DropAlias":                     109,
	"AlterAlias":                    110,
	"AlterCollection":               111,
	"RenameCollection":              112,
	"DescribeAlias":                 113,
	"ListAliases":                   114,
	"CreatePartition":               200,
	"DropPartition":                 201,
	"HasPartition":                  202,
	"DescribePartition":             203,
	"ShowPartitions":                204,
	"LoadPartitions":                205,
	"ReleasePartitions":             206,
	"ShowSegments":                  250,
	"DescribeSegment":               251,
	"LoadSegments":                  252,
	"ReleaseSegments":               253,
	"HandoffSegments":               254,
	"LoadBalanceSegments":           255,
	"DescribeSegments":              256,
	"FederListIndexedSegment":       257,
	"FederDescribeSegmentIndexData": 258,
	"CreateIndex":                   300,
	"DescribeIndex":                 301,
	"DropIndex":                     302,
	"GetIndexStatistics":            303,
	"Insert":                        400,
	"Delete":                        401,
	"Flush":                         402,
	"ResendSegmentStats":            403,
	"Upsert":                        404,
	"Search":                        500,
	"SearchResult":                  501,
	"GetIndexState":                 502,
	"GetIndexBuildProgress":         503,
	"GetCollectionStatistics":       504,
	"GetPartitionStatistics":        505,
	"Retrieve":                      506,
	"RetrieveResult":                507,
	"WatchDmChannels":               508,
	"RemoveDmChannels":              509,
	"WatchQueryChannels":            510,
	"RemoveQueryChannels":           511,
	"SealedSegmentsChangeInfo":      512,
	"WatchDeltaChannels":            513,
	"GetShardLeaders":               514,
	"GetReplicas":                   515,
	"UnsubDmChannel":                516,
	"GetDistribution":               517,
	"SyncDistribution":              518,
	"SegmentInfo":                   600,
	"SystemInfo":                    601,
	"GetRecoveryInfo":               602,
	"GetSegmentState":               603,
	"TimeTick":                      1200,
	"QueryNodeStats":                1201,
	"LoadIndex":                     1202,
	"RequestID":                     1203,
	"RequestTSO":                    1204,
	"AllocateSegment":               1205,
	"SegmentStatistics":             1206,
	"SegmentFlushDone":              1207,
	"DataNodeTt":                    1208,
	"Connect":                       1209,
	"ListClientInfos":               1210,
	"AllocTimestamp":                1211,
	"CreateCredential":              1500,
	"GetCredential":                 1501,
	"DeleteCredential":              1502,
	"UpdateCredential":              1503,
	"ListCredUsernames":             1504,
	"CreateRole":                    1600,
	"DropRole":                      1601,
	"OperateUserRole":               1602,
	"SelectRole":                    1603,
	"SelectUser":                    1604,
	"SelectResource":                1605,
	"OperatePrivilege":              1606,
	"SelectGrant":                   1607,
	"RefreshPolicyInfoCache":        1608,
	"ListPolicy":                    1609,
	"CreateResourceGroup":           1700,
	"DropResourceGroup":             1701,
	"ListResourceGroups":            1702,
	"DescribeResourceGroup":         1703,
	"TransferNode":                  1704,
	"TransferReplica":               1705,
	"CreateDatabase":                1801,
	"DropDatabase":                  1802,
	"ListDatabases":                 1803,
}

func (x MsgType) String() string {
	return proto.EnumName(MsgType_name, int32(x))
}

func (MsgType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{4}
}

type DslType int32

const (
	DslType_Dsl        DslType = 0
	DslType_BoolExprV1 DslType = 1
)

var DslType_name = map[int32]string{
	0: "Dsl",
	1: "BoolExprV1",
}

var DslType_value = map[string]int32{
	"Dsl":        0,
	"BoolExprV1": 1,
}

func (x DslType) String() string {
	return proto.EnumName(DslType_name, int32(x))
}

func (DslType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{5}
}

type CompactionState int32

const (
	CompactionState_UndefiedState CompactionState = 0
	CompactionState_Executing     CompactionState = 1
	CompactionState_Completed     CompactionState = 2
)

var CompactionState_name = map[int32]string{
	0: "UndefiedState",
	1: "Executing",
	2: "Completed",
}

var CompactionState_value = map[string]int32{
	"UndefiedState": 0,
	"Executing":     1,
	"Completed":     2,
}

func (x CompactionState) String() string {
	return proto.EnumName(CompactionState_name, int32(x))
}

func (CompactionState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{6}
}

type ConsistencyLevel int32

const (
	ConsistencyLevel_Strong     ConsistencyLevel = 0
	ConsistencyLevel_Session    ConsistencyLevel = 1
	ConsistencyLevel_Bounded    ConsistencyLevel = 2
	ConsistencyLevel_Eventually ConsistencyLevel = 3
	ConsistencyLevel_Customized ConsistencyLevel = 4
)

var ConsistencyLevel_name = map[int32]string{
	0: "Strong",
	1: "Session",
	2: "Bounded",
	3: "Eventually",
	4: "Customized",
}

var ConsistencyLevel_value = map[string]int32{
	"Strong":     0,
	"Session":    1,
	"Bounded":    2,
	"Eventually": 3,
	"Customized": 4,
}

func (x ConsistencyLevel) String() string {
	return proto.EnumName(ConsistencyLevel_name, int32(x))
}

func (ConsistencyLevel) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{7}
}

type ImportState int32

const (
	ImportState_ImportPending          ImportState = 0
	ImportState_ImportFailed           ImportState = 1
	ImportState_ImportStarted          ImportState = 2
	ImportState_ImportPersisted        ImportState = 5
	ImportState_ImportFlushed          ImportState = 8
	ImportState_ImportCompleted        ImportState = 6
	ImportState_ImportFailedAndCleaned ImportState = 7
)

var ImportState_name = map[int32]string{
	0: "ImportPending",
	1: "ImportFailed",
	2: "ImportStarted",
	5: "ImportPersisted",
	8: "ImportFlushed",
	6: "ImportCompleted",
	7: "ImportFailedAndCleaned",
}

var ImportState_value = map[string]int32{
	"ImportPending":          0,
	"ImportFailed":           1,
	"ImportStarted":          2,
	"ImportPersisted":        5,
	"ImportFlushed":          8,
	"ImportCompleted":        6,
	"ImportFailedAndCleaned": 7,
}

func (x ImportState) String() string {
	return proto.EnumName(ImportState_name, int32(x))
}

func (ImportState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{8}
}

type ObjectType int32

const (
	ObjectType_Collection ObjectType = 0
	ObjectType_Global     ObjectType = 1
	ObjectType_User       ObjectType = 2
)

var ObjectType_name = map[int32]string{
	0: "Collection",
	1: "Global",
	2: "User",
}

var ObjectType_value = map[string]int32{
	"Collection": 0,
	"Global":     1,
	"User":       2,
}

func (x ObjectType) String() string {
	return proto.EnumName(ObjectType_name, int32(x))
}

func (ObjectType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{9}
}

type ObjectPrivilege int32

const (
	ObjectPrivilege_PrivilegeAll                   ObjectPrivilege = 0
	ObjectPrivilege_PrivilegeCreateCollection      ObjectPrivilege = 1
	ObjectPrivilege_PrivilegeDropCollection        ObjectPrivilege = 2
	ObjectPrivilege_PrivilegeDescribeCollection    ObjectPrivilege = 3
	ObjectPrivilege_PrivilegeShowCollections       ObjectPrivilege = 4
	ObjectPrivilege_PrivilegeLoad                  ObjectPrivilege = 5
	ObjectPrivilege_PrivilegeRelease               ObjectPrivilege = 6
	ObjectPrivilege_PrivilegeCompaction            ObjectPrivilege = 7
	ObjectPrivilege_PrivilegeInsert                ObjectPrivilege = 8
	ObjectPrivilege_PrivilegeDelete                ObjectPrivilege = 9
	ObjectPrivilege_PrivilegeGetStatistics         ObjectPrivilege = 10
	ObjectPrivilege_PrivilegeCreateIndex           ObjectPrivilege = 11
	ObjectPrivilege_PrivilegeIndexDetail           ObjectPrivilege = 12
	ObjectPrivilege_PrivilegeDropIndex             ObjectPrivilege = 13
	ObjectPrivilege_PrivilegeSearch                ObjectPrivilege = 14
	ObjectPrivilege_PrivilegeFlush                 ObjectPrivilege = 15
	ObjectPrivilege_PrivilegeQuery                 ObjectPrivilege = 16
	ObjectPrivilege_PrivilegeLoadBalance           ObjectPrivilege = 17
	ObjectPrivilege_PrivilegeImport                ObjectPrivilege = 18
	ObjectPrivilege_PrivilegeCreateOwnership       ObjectPrivilege = 19
	ObjectPrivilege_PrivilegeUpdateUser            ObjectPrivilege = 20
	ObjectPrivilege_PrivilegeDropOwnership         ObjectPrivilege = 21
	ObjectPrivilege_PrivilegeSelectOwnership       ObjectPrivilege = 22
	ObjectPrivilege_PrivilegeManageOwnership       ObjectPrivilege = 23
	ObjectPrivilege_PrivilegeSelectUser            ObjectPrivilege = 24
	ObjectPrivilege_PrivilegeUpsert                ObjectPrivilege = 25
	ObjectPrivilege_PrivilegeCreateResourceGroup   ObjectPrivilege = 26
	ObjectPrivilege_PrivilegeDropResourceGroup     ObjectPrivilege = 27
	ObjectPrivilege_PrivilegeDescribeResourceGroup ObjectPrivilege = 28
	ObjectPrivilege_PrivilegeListResourceGroups    ObjectPrivilege = 29
	ObjectPrivilege_PrivilegeTransferNode          ObjectPrivilege = 30
	ObjectPrivilege_PrivilegeTransferReplica       ObjectPrivilege = 31
	ObjectPrivilege_PrivilegeGetLoadingProgress    ObjectPrivilege = 32
	ObjectPrivilege_PrivilegeGetLoadState          ObjectPrivilege = 33
	ObjectPrivilege_PrivilegeRenameCollection      ObjectPrivilege = 34
	ObjectPrivilege_PrivilegeCreateDatabase        ObjectPrivilege = 35
	ObjectPrivilege_PrivilegeDropDatabase          ObjectPrivilege = 36
	ObjectPrivilege_PrivilegeListDatabases         ObjectPrivilege = 37
	ObjectPrivilege_PrivilegeFlushAll              ObjectPrivilege = 38
)

var ObjectPrivilege_name = map[int32]string{
	0:  "PrivilegeAll",
	1:  "PrivilegeCreateCollection",
	2:  "PrivilegeDropCollection",
	3:  "PrivilegeDescribeCollection",
	4:  "PrivilegeShowCollections",
	5:  "PrivilegeLoad",
	6:  "PrivilegeRelease",
	7:  "PrivilegeCompaction",
	8:  "PrivilegeInsert",
	9:  "PrivilegeDelete",
	10: "PrivilegeGetStatistics",
	11: "PrivilegeCreateIndex",
	12: "PrivilegeIndexDetail",
	13: "PrivilegeDropIndex",
	14: "PrivilegeSearch",
	15: "PrivilegeFlush",
	16: "PrivilegeQuery",
	17: "PrivilegeLoadBalance",
	18: "PrivilegeImport",
	19: "PrivilegeCreateOwnership",
	20: "PrivilegeUpdateUser",
	21: "PrivilegeDropOwnership",
	22: "PrivilegeSelectOwnership",
	23: "PrivilegeManageOwnership",
	24: "PrivilegeSelectUser",
	25: "PrivilegeUpsert",
	26: "PrivilegeCreateResourceGroup",
	27: "PrivilegeDropResourceGroup",
	28: "PrivilegeDescribeResourceGroup",
	29: "PrivilegeListResourceGroups",
	30: "PrivilegeTransferNode",
	31: "PrivilegeTransferReplica",
	32: "PrivilegeGetLoadingProgress",
	33: "PrivilegeGetLoadState",
	34: "PrivilegeRenameCollection",
	35: "PrivilegeCreateDatabase",
	36: "PrivilegeDropDatabase",
	37: "PrivilegeListDatabases",
	38: "PrivilegeFlushAll",
}

var ObjectPrivilege_value = map[string]int32{
	"PrivilegeAll":                   0,
	"PrivilegeCreateCollection":      1,
	"PrivilegeDropCollection":        2,
	"PrivilegeDescribeCollection":    3,
	"PrivilegeShowCollections":       4,
	"PrivilegeLoad":                  5,
	"PrivilegeRelease":               6,
	"PrivilegeCompaction":            7,
	"PrivilegeInsert":                8,
	"PrivilegeDelete":                9,
	"PrivilegeGetStatistics":         10,
	"PrivilegeCreateIndex":           11,
	"PrivilegeIndexDetail":           12,
	"PrivilegeDropIndex":             13,
	"PrivilegeSearch":                14,
	"PrivilegeFlush":                 15,
	"PrivilegeQuery":                 16,
	"PrivilegeLoadBalance":           17,
	"PrivilegeImport":                18,
	"PrivilegeCreateOwnership":       19,
	"PrivilegeUpdateUser":            20,
	"PrivilegeDropOwnership":         21,
	"PrivilegeSelectOwnership":       22,
	"PrivilegeManageOwnership":       23,
	"PrivilegeSelectUser":            24,
	"PrivilegeUpsert":                25,
	"PrivilegeCreateResourceGroup":   26,
	"PrivilegeDropResourceGroup":     27,
	"PrivilegeDescribeResourceGroup": 28,
	"PrivilegeListResourceGroups":    29,
	"PrivilegeTransferNode":          30,
	"PrivilegeTransferReplica":       31,
	"PrivilegeGetLoadingProgress":    32,
	"PrivilegeGetLoadState":          33,
	"PrivilegeRenameCollection":      34,
	"PrivilegeCreateDatabase":        35,
	"PrivilegeDropDatabase":          36,
	"PrivilegeListDatabases":         37,
	"PrivilegeFlushAll":              38,
}

func (x ObjectPrivilege) String() string {
	return proto.EnumName(ObjectPrivilege_name, int32(x))
}

func (ObjectPrivilege) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{10}
}

type StateCode int32

const (
	StateCode_Initializing StateCode = 0
	StateCode_Healthy      StateCode = 1
	StateCode_Abnormal     StateCode = 2
	StateCode_StandBy      StateCode = 3
	StateCode_Stopping     StateCode = 4
)

var StateCode_name = map[int32]string{
	0: "Initializing",
	1: "Healthy",
	2: "Abnormal",
	3: "StandBy",
	4: "Stopping",
}

var StateCode_value = map[string]int32{
	"Initializing": 0,
	"Healthy":      1,
	"Abnormal":     2,
	"StandBy":      3,
	"Stopping":     4,
}

func (x StateCode) String() string {
	return proto.EnumName(StateCode_name, int32(x))
}

func (StateCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{11}
}

type LoadState int32

const (
	LoadState_LoadStateNotExist LoadState = 0
	LoadState_LoadStateNotLoad  LoadState = 1
	LoadState_LoadStateLoading  LoadState = 2
	LoadState_LoadStateLoaded   LoadState = 3
)

var LoadState_name = map[int32]string{
	0: "LoadStateNotExist",
	1: "LoadStateNotLoad",
	2: "LoadStateLoading",
	3: "LoadStateLoaded",
}

var LoadState_value = map[string]int32{
	"LoadStateNotExist": 0,
	"LoadStateNotLoad":  1,
	"LoadStateLoading":  2,
	"LoadStateLoaded":   3,
}

func (x LoadState) String() string {
	return proto.EnumName(LoadState_name, int32(x))
}

func (LoadState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{12}
}

type Status struct {
	ErrorCode            ErrorCode `protobuf:"varint,1,opt,name=error_code,json=errorCode,proto3,enum=milvus.proto.common.ErrorCode" json:"error_code,omitempty"`
	Reason               string    `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	Code                 int32     `protobuf:"varint,3,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Status) Reset()         { *m = Status{} }
func (m *Status) String() string { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()    {}
func (*Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{0}
}

func (m *Status) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Status.Unmarshal(m, b)
}
func (m *Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Status.Marshal(b, m, deterministic)
}
func (m *Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Status.Merge(m, src)
}
func (m *Status) XXX_Size() int {
	return xxx_messageInfo_Status.Size(m)
}
func (m *Status) XXX_DiscardUnknown() {
	xxx_messageInfo_Status.DiscardUnknown(m)
}

var xxx_messageInfo_Status proto.InternalMessageInfo

func (m *Status) GetErrorCode() ErrorCode {
	if m != nil {
		return m.ErrorCode
	}
	return ErrorCode_Success
}

func (m *Status) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

func (m *Status) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

type KeyValuePair struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeyValuePair) Reset()         { *m = KeyValuePair{} }
func (m *KeyValuePair) String() string { return proto.CompactTextString(m) }
func (*KeyValuePair) ProtoMessage()    {}
func (*KeyValuePair) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{1}
}

func (m *KeyValuePair) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeyValuePair.Unmarshal(m, b)
}
func (m *KeyValuePair) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeyValuePair.Marshal(b, m, deterministic)
}
func (m *KeyValuePair) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyValuePair.Merge(m, src)
}
func (m *KeyValuePair) XXX_Size() int {
	return xxx_messageInfo_KeyValuePair.Size(m)
}
func (m *KeyValuePair) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyValuePair.DiscardUnknown(m)
}

var xxx_messageInfo_KeyValuePair proto.InternalMessageInfo

func (m *KeyValuePair) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *KeyValuePair) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type KeyDataPair struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeyDataPair) Reset()         { *m = KeyDataPair{} }
func (m *KeyDataPair) String() string { return proto.CompactTextString(m) }
func (*KeyDataPair) ProtoMessage()    {}
func (*KeyDataPair) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{2}
}

func (m *KeyDataPair) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeyDataPair.Unmarshal(m, b)
}
func (m *KeyDataPair) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeyDataPair.Marshal(b, m, deterministic)
}
func (m *KeyDataPair) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyDataPair.Merge(m, src)
}
func (m *KeyDataPair) XXX_Size() int {
	return xxx_messageInfo_KeyDataPair.Size(m)
}
func (m *KeyDataPair) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyDataPair.DiscardUnknown(m)
}

var xxx_messageInfo_KeyDataPair proto.InternalMessageInfo

func (m *KeyDataPair) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *KeyDataPair) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type Blob struct {
	Value                []byte   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Blob) Reset()         { *m = Blob{} }
func (m *Blob) String() string { return proto.CompactTextString(m) }
func (*Blob) ProtoMessage()    {}
func (*Blob) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{3}
}

func (m *Blob) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Blob.Unmarshal(m, b)
}
func (m *Blob) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Blob.Marshal(b, m, deterministic)
}
func (m *Blob) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Blob.Merge(m, src)
}
func (m *Blob) XXX_Size() int {
	return xxx_messageInfo_Blob.Size(m)
}
func (m *Blob) XXX_DiscardUnknown() {
	xxx_messageInfo_Blob.DiscardUnknown(m)
}

var xxx_messageInfo_Blob proto.InternalMessageInfo

func (m *Blob) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type PlaceholderValue struct {
	Tag  string          `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	Type PlaceholderType `protobuf:"varint,2,opt,name=type,proto3,enum=milvus.proto.common.PlaceholderType" json:"type,omitempty"`
	// values is a 2d-array, every array contains a vector
	Values               [][]byte `protobuf:"bytes,3,rep,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlaceholderValue) Reset()         { *m = PlaceholderValue{} }
func (m *PlaceholderValue) String() string { return proto.CompactTextString(m) }
func (*PlaceholderValue) ProtoMessage()    {}
func (*PlaceholderValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{4}
}

func (m *PlaceholderValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlaceholderValue.Unmarshal(m, b)
}
func (m *PlaceholderValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlaceholderValue.Marshal(b, m, deterministic)
}
func (m *PlaceholderValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlaceholderValue.Merge(m, src)
}
func (m *PlaceholderValue) XXX_Size() int {
	return xxx_messageInfo_PlaceholderValue.Size(m)
}
func (m *PlaceholderValue) XXX_DiscardUnknown() {
	xxx_messageInfo_PlaceholderValue.DiscardUnknown(m)
}

var xxx_messageInfo_PlaceholderValue proto.InternalMessageInfo

func (m *PlaceholderValue) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

func (m *PlaceholderValue) GetType() PlaceholderType {
	if m != nil {
		return m.Type
	}
	return PlaceholderType_None
}

func (m *PlaceholderValue) GetValues() [][]byte {
	if m != nil {
		return m.Values
	}
	return nil
}

type PlaceholderGroup struct {
	Placeholders         []*PlaceholderValue `protobuf:"bytes,1,rep,name=placeholders,proto3" json:"placeholders,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *PlaceholderGroup) Reset()         { *m = PlaceholderGroup{} }
func (m *PlaceholderGroup) String() string { return proto.CompactTextString(m) }
func (*PlaceholderGroup) ProtoMessage()    {}
func (*PlaceholderGroup) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{5}
}

func (m *PlaceholderGroup) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlaceholderGroup.Unmarshal(m, b)
}
func (m *PlaceholderGroup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlaceholderGroup.Marshal(b, m, deterministic)
}
func (m *PlaceholderGroup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlaceholderGroup.Merge(m, src)
}
func (m *PlaceholderGroup) XXX_Size() int {
	return xxx_messageInfo_PlaceholderGroup.Size(m)
}
func (m *PlaceholderGroup) XXX_DiscardUnknown() {
	xxx_messageInfo_PlaceholderGroup.DiscardUnknown(m)
}

var xxx_messageInfo_PlaceholderGroup proto.InternalMessageInfo

func (m *PlaceholderGroup) GetPlaceholders() []*PlaceholderValue {
	if m != nil {
		return m.Placeholders
	}
	return nil
}

type Address struct {
	Ip                   string   `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Port                 int64    `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Address) Reset()         { *m = Address{} }
func (m *Address) String() string { return proto.CompactTextString(m) }
func (*Address) ProtoMessage()    {}
func (*Address) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{6}
}

func (m *Address) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Address.Unmarshal(m, b)
}
func (m *Address) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Address.Marshal(b, m, deterministic)
}
func (m *Address) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Address.Merge(m, src)
}
func (m *Address) XXX_Size() int {
	return xxx_messageInfo_Address.Size(m)
}
func (m *Address) XXX_DiscardUnknown() {
	xxx_messageInfo_Address.DiscardUnknown(m)
}

var xxx_messageInfo_Address proto.InternalMessageInfo

func (m *Address) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *Address) GetPort() int64 {
	if m != nil {
		return m.Port
	}
	return 0
}

type MsgBase struct {
	MsgType              MsgType           `protobuf:"varint,1,opt,name=msg_type,json=msgType,proto3,enum=milvus.proto.common.MsgType" json:"msg_type,omitempty"`
	MsgID                int64             `protobuf:"varint,2,opt,name=msgID,proto3" json:"msgID,omitempty"`
	Timestamp            uint64            `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	SourceID             int64             `protobuf:"varint,4,opt,name=sourceID,proto3" json:"sourceID,omitempty"`
	TargetID             int64             `protobuf:"varint,5,opt,name=targetID,proto3" json:"targetID,omitempty"`
	Properties           map[string]string `protobuf:"bytes,6,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *MsgBase) Reset()         { *m = MsgBase{} }
func (m *MsgBase) String() string { return proto.CompactTextString(m) }
func (*MsgBase) ProtoMessage()    {}
func (*MsgBase) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{7}
}

func (m *MsgBase) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgBase.Unmarshal(m, b)
}
func (m *MsgBase) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgBase.Marshal(b, m, deterministic)
}
func (m *MsgBase) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgBase.Merge(m, src)
}
func (m *MsgBase) XXX_Size() int {
	return xxx_messageInfo_MsgBase.Size(m)
}
func (m *MsgBase) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgBase.DiscardUnknown(m)
}

var xxx_messageInfo_MsgBase proto.InternalMessageInfo

func (m *MsgBase) GetMsgType() MsgType {
	if m != nil {
		return m.MsgType
	}
	return MsgType_Undefined
}

func (m *MsgBase) GetMsgID() int64 {
	if m != nil {
		return m.MsgID
	}
	return 0
}

func (m *MsgBase) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *MsgBase) GetSourceID() int64 {
	if m != nil {
		return m.SourceID
	}
	return 0
}

func (m *MsgBase) GetTargetID() int64 {
	if m != nil {
		return m.TargetID
	}
	return 0
}

func (m *MsgBase) GetProperties() map[string]string {
	if m != nil {
		return m.Properties
	}
	return nil
}

// Don't Modify This. @czs
type MsgHeader struct {
	Base                 *MsgBase `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgHeader) Reset()         { *m = MsgHeader{} }
func (m *MsgHeader) String() string { return proto.CompactTextString(m) }
func (*MsgHeader) ProtoMessage()    {}
func (*MsgHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{8}
}

func (m *MsgHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgHeader.Unmarshal(m, b)
}
func (m *MsgHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgHeader.Marshal(b, m, deterministic)
}
func (m *MsgHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgHeader.Merge(m, src)
}
func (m *MsgHeader) XXX_Size() int {
	return xxx_messageInfo_MsgHeader.Size(m)
}
func (m *MsgHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgHeader.DiscardUnknown(m)
}

var xxx_messageInfo_MsgHeader proto.InternalMessageInfo

func (m *MsgHeader) GetBase() *MsgBase {
	if m != nil {
		return m.Base
	}
	return nil
}

// Don't Modify This. @czs
type DMLMsgHeader struct {
	Base                 *MsgBase `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	ShardName            string   `protobuf:"bytes,2,opt,name=shardName,proto3" json:"shardName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DMLMsgHeader) Reset()         { *m = DMLMsgHeader{} }
func (m *DMLMsgHeader) String() string { return proto.CompactTextString(m) }
func (*DMLMsgHeader) ProtoMessage()    {}
func (*DMLMsgHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{9}
}

func (m *DMLMsgHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DMLMsgHeader.Unmarshal(m, b)
}
func (m *DMLMsgHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DMLMsgHeader.Marshal(b, m, deterministic)
}
func (m *DMLMsgHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DMLMsgHeader.Merge(m, src)
}
func (m *DMLMsgHeader) XXX_Size() int {
	return xxx_messageInfo_DMLMsgHeader.Size(m)
}
func (m *DMLMsgHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_DMLMsgHeader.DiscardUnknown(m)
}

var xxx_messageInfo_DMLMsgHeader proto.InternalMessageInfo

func (m *DMLMsgHeader) GetBase() *MsgBase {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *DMLMsgHeader) GetShardName() string {
	if m != nil {
		return m.ShardName
	}
	return ""
}

type PrivilegeExt struct {
	ObjectType           ObjectType      `protobuf:"varint,1,opt,name=object_type,json=objectType,proto3,enum=milvus.proto.common.ObjectType" json:"object_type,omitempty"`
	ObjectPrivilege      ObjectPrivilege `protobuf:"varint,2,opt,name=object_privilege,json=objectPrivilege,proto3,enum=milvus.proto.common.ObjectPrivilege" json:"object_privilege,omitempty"`
	ObjectNameIndex      int32           `protobuf:"varint,3,opt,name=object_name_index,json=objectNameIndex,proto3" json:"object_name_index,omitempty"`
	ObjectNameIndexs     int32           `protobuf:"varint,4,opt,name=object_name_indexs,json=objectNameIndexs,proto3" json:"object_name_indexs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *PrivilegeExt) Reset()         { *m = PrivilegeExt{} }
func (m *PrivilegeExt) String() string { return proto.CompactTextString(m) }
func (*PrivilegeExt) ProtoMessage()    {}
func (*PrivilegeExt) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{10}
}

func (m *PrivilegeExt) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrivilegeExt.Unmarshal(m, b)
}
func (m *PrivilegeExt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrivilegeExt.Marshal(b, m, deterministic)
}
func (m *PrivilegeExt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrivilegeExt.Merge(m, src)
}
func (m *PrivilegeExt) XXX_Size() int {
	return xxx_messageInfo_PrivilegeExt.Size(m)
}
func (m *PrivilegeExt) XXX_DiscardUnknown() {
	xxx_messageInfo_PrivilegeExt.DiscardUnknown(m)
}

var xxx_messageInfo_PrivilegeExt proto.InternalMessageInfo

func (m *PrivilegeExt) GetObjectType() ObjectType {
	if m != nil {
		return m.ObjectType
	}
	return ObjectType_Collection
}

func (m *PrivilegeExt) GetObjectPrivilege() ObjectPrivilege {
	if m != nil {
		return m.ObjectPrivilege
	}
	return ObjectPrivilege_PrivilegeAll
}

func (m *PrivilegeExt) GetObjectNameIndex() int32 {
	if m != nil {
		return m.ObjectNameIndex
	}
	return 0
}

func (m *PrivilegeExt) GetObjectNameIndexs() int32 {
	if m != nil {
		return m.ObjectNameIndexs
	}
	return 0
}

type SegmentStats struct {
	SegmentID            int64    `protobuf:"varint,1,opt,name=SegmentID,proto3" json:"SegmentID,omitempty"`
	NumRows              int64    `protobuf:"varint,2,opt,name=NumRows,proto3" json:"NumRows,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SegmentStats) Reset()         { *m = SegmentStats{} }
func (m *SegmentStats) String() string { return proto.CompactTextString(m) }
func (*SegmentStats) ProtoMessage()    {}
func (*SegmentStats) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{11}
}

func (m *SegmentStats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SegmentStats.Unmarshal(m, b)
}
func (m *SegmentStats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SegmentStats.Marshal(b, m, deterministic)
}
func (m *SegmentStats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SegmentStats.Merge(m, src)
}
func (m *SegmentStats) XXX_Size() int {
	return xxx_messageInfo_SegmentStats.Size(m)
}
func (m *SegmentStats) XXX_DiscardUnknown() {
	xxx_messageInfo_SegmentStats.DiscardUnknown(m)
}

var xxx_messageInfo_SegmentStats proto.InternalMessageInfo

func (m *SegmentStats) GetSegmentID() int64 {
	if m != nil {
		return m.SegmentID
	}
	return 0
}

func (m *SegmentStats) GetNumRows() int64 {
	if m != nil {
		return m.NumRows
	}
	return 0
}

type ClientInfo struct {
	// sdk_type can be `python`, `golang`, `nodejs` and etc. It's not proper to make `sdk_type` an
	// enumerate type, since we cannot always update the enum value everytime when newly sdk is supported.
	SdkType    string `protobuf:"bytes,1,opt,name=sdk_type,json=sdkType,proto3" json:"sdk_type,omitempty"`
	SdkVersion string `protobuf:"bytes,2,opt,name=sdk_version,json=sdkVersion,proto3" json:"sdk_version,omitempty"`
	LocalTime  string `protobuf:"bytes,3,opt,name=local_time,json=localTime,proto3" json:"local_time,omitempty"`
	User       string `protobuf:"bytes,4,opt,name=user,proto3" json:"user,omitempty"`
	Host       string `protobuf:"bytes,5,opt,name=host,proto3" json:"host,omitempty"`
	// reserved for newly-added feature if necessary.
	Reserved             map[string]string `protobuf:"bytes,6,rep,name=reserved,proto3" json:"reserved,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ClientInfo) Reset()         { *m = ClientInfo{} }
func (m *ClientInfo) String() string { return proto.CompactTextString(m) }
func (*ClientInfo) ProtoMessage()    {}
func (*ClientInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{12}
}

func (m *ClientInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientInfo.Unmarshal(m, b)
}
func (m *ClientInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientInfo.Marshal(b, m, deterministic)
}
func (m *ClientInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientInfo.Merge(m, src)
}
func (m *ClientInfo) XXX_Size() int {
	return xxx_messageInfo_ClientInfo.Size(m)
}
func (m *ClientInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ClientInfo proto.InternalMessageInfo

func (m *ClientInfo) GetSdkType() string {
	if m != nil {
		return m.SdkType
	}
	return ""
}

func (m *ClientInfo) GetSdkVersion() string {
	if m != nil {
		return m.SdkVersion
	}
	return ""
}

func (m *ClientInfo) GetLocalTime() string {
	if m != nil {
		return m.LocalTime
	}
	return ""
}

func (m *ClientInfo) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *ClientInfo) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *ClientInfo) GetReserved() map[string]string {
	if m != nil {
		return m.Reserved
	}
	return nil
}

type ServerInfo struct {
	BuildTags  string `protobuf:"bytes,1,opt,name=build_tags,json=buildTags,proto3" json:"build_tags,omitempty"`
	BuildTime  string `protobuf:"bytes,2,opt,name=build_time,json=buildTime,proto3" json:"build_time,omitempty"`
	GitCommit  string `protobuf:"bytes,3,opt,name=git_commit,json=gitCommit,proto3" json:"git_commit,omitempty"`
	GoVersion  string `protobuf:"bytes,4,opt,name=go_version,json=goVersion,proto3" json:"go_version,omitempty"`
	DeployMode string `protobuf:"bytes,5,opt,name=deploy_mode,json=deployMode,proto3" json:"deploy_mode,omitempty"`
	// reserved for newly-added feature if necessary.
	Reserved             map[string]string `protobuf:"bytes,6,rep,name=reserved,proto3" json:"reserved,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ServerInfo) Reset()         { *m = ServerInfo{} }
func (m *ServerInfo) String() string { return proto.CompactTextString(m) }
func (*ServerInfo) ProtoMessage()    {}
func (*ServerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{13}
}

func (m *ServerInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerInfo.Unmarshal(m, b)
}
func (m *ServerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerInfo.Marshal(b, m, deterministic)
}
func (m *ServerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerInfo.Merge(m, src)
}
func (m *ServerInfo) XXX_Size() int {
	return xxx_messageInfo_ServerInfo.Size(m)
}
func (m *ServerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ServerInfo proto.InternalMessageInfo

func (m *ServerInfo) GetBuildTags() string {
	if m != nil {
		return m.BuildTags
	}
	return ""
}

func (m *ServerInfo) GetBuildTime() string {
	if m != nil {
		return m.BuildTime
	}
	return ""
}

func (m *ServerInfo) GetGitCommit() string {
	if m != nil {
		return m.GitCommit
	}
	return ""
}

func (m *ServerInfo) GetGoVersion() string {
	if m != nil {
		return m.GoVersion
	}
	return ""
}

func (m *ServerInfo) GetDeployMode() string {
	if m != nil {
		return m.DeployMode
	}
	return ""
}

func (m *ServerInfo) GetReserved() map[string]string {
	if m != nil {
		return m.Reserved
	}
	return nil
}

var E_PrivilegeExtObj = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: (*PrivilegeExt)(nil),
	Field:         1001,
	Name:          "milvus.proto.common.privilege_ext_obj",
	Tag:           "bytes,1001,opt,name=privilege_ext_obj",
	Filename:      "common.proto",
}

func init() {
	proto.RegisterEnum("milvus.proto.common.ErrorCode", ErrorCode_name, ErrorCode_value)
	proto.RegisterEnum("milvus.proto.common.IndexState", IndexState_name, IndexState_value)
	proto.RegisterEnum("milvus.proto.common.SegmentState", SegmentState_name, SegmentState_value)
	proto.RegisterEnum("milvus.proto.common.PlaceholderType", PlaceholderType_name, PlaceholderType_value)
	proto.RegisterEnum("milvus.proto.common.MsgType", MsgType_name, MsgType_value)
	proto.RegisterEnum("milvus.proto.common.DslType", DslType_name, DslType_value)
	proto.RegisterEnum("milvus.proto.common.CompactionState", CompactionState_name, CompactionState_value)
	proto.RegisterEnum("milvus.proto.common.ConsistencyLevel", ConsistencyLevel_name, ConsistencyLevel_value)
	proto.RegisterEnum("milvus.proto.common.ImportState", ImportState_name, ImportState_value)
	proto.RegisterEnum("milvus.proto.common.ObjectType", ObjectType_name, ObjectType_value)
	proto.RegisterEnum("milvus.proto.common.ObjectPrivilege", ObjectPrivilege_name, ObjectPrivilege_value)
	proto.RegisterEnum("milvus.proto.common.StateCode", StateCode_name, StateCode_value)
	proto.RegisterEnum("milvus.proto.common.LoadState", LoadState_name, LoadState_value)
	proto.RegisterType((*Status)(nil), "milvus.proto.common.Status")
	proto.RegisterType((*KeyValuePair)(nil), "milvus.proto.common.KeyValuePair")
	proto.RegisterType((*KeyDataPair)(nil), "milvus.proto.common.KeyDataPair")
	proto.RegisterType((*Blob)(nil), "milvus.proto.common.Blob")
	proto.RegisterType((*PlaceholderValue)(nil), "milvus.proto.common.PlaceholderValue")
	proto.RegisterType((*PlaceholderGroup)(nil), "milvus.proto.common.PlaceholderGroup")
	proto.RegisterType((*Address)(nil), "milvus.proto.common.Address")
	proto.RegisterType((*MsgBase)(nil), "milvus.proto.common.MsgBase")
	proto.RegisterMapType((map[string]string)(nil), "milvus.proto.common.MsgBase.PropertiesEntry")
	proto.RegisterType((*MsgHeader)(nil), "milvus.proto.common.MsgHeader")
	proto.RegisterType((*DMLMsgHeader)(nil), "milvus.proto.common.DMLMsgHeader")
	proto.RegisterType((*PrivilegeExt)(nil), "milvus.proto.common.PrivilegeExt")
	proto.RegisterType((*SegmentStats)(nil), "milvus.proto.common.SegmentStats")
	proto.RegisterType((*ClientInfo)(nil), "milvus.proto.common.ClientInfo")
	proto.RegisterMapType((map[string]string)(nil), "milvus.proto.common.ClientInfo.ReservedEntry")
	proto.RegisterType((*ServerInfo)(nil), "milvus.proto.common.ServerInfo")
	proto.RegisterMapType((map[string]string)(nil), "milvus.proto.common.ServerInfo.ReservedEntry")
	proto.RegisterExtension(E_PrivilegeExtObj)
}

func init() { proto.RegisterFile("common.proto", fileDescriptor_555bd8c177793206) }

var fileDescriptor_555bd8c177793206 = []byte{
	// 3374 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x79, 0x59, 0x70, 0x5c, 0x49,
	0x56, 0xb6, 0x6b, 0xd1, 0x52, 0x59, 0xa5, 0x52, 0x3a, 0x6d, 0xd9, 0xb2, 0x6c, 0xd9, 0xea, 0x9a,
	0x9e, 0xf9, 0xfd, 0x8b, 0xb6, 0x3c, 0xed, 0x6e, 0x7a, 0x9a, 0x21, 0x3a, 0x02, 0xa9, 0x4a, 0x92,
	0x2b, 0x5a, 0xdb, 0x5c, 0xc9, 0x86, 0x20, 0x02, 0x14, 0x59, 0xf7, 0x1e, 0x95, 0xb2, 0x7d, 0xeb,
	0xe6, 0x9d, 0xcc, 0x2c, 0xd9, 0x35, 0x4f, 0x33, 0xcd, 0x12, 0x01, 0xbc, 0xb0, 0x45, 0xf0, 0x46,
	0x40, 0x04, 0x7b, 0xb0, 0x0d, 0x0c, 0xeb, 0xbc, 0x00, 0xc3, 0x32, 0xc3, 0xf6, 0xcc, 0x0e, 0x8f,
	0xf0, 0xce, 0x3a, 0x3d, 0x0b, 0x71, 0x32, 0xef, 0x5a, 0x76, 0xc3, 0x10, 0x04, 0x6f, 0x37, 0xbf,
	0x73, 0xf2, 0x6c, 0x79, 0xf2, 0x9c, 0x93, 0x55, 0xa4, 0xe5, 0xcb, 0xd1, 0x48, 0x46, 0x1b, 0xb1,
	0x92, 0x46, 0xb2, 0x2b, 0x23, 0x11, 0x5e, 0x8c, 0xb5, 0x5b, 0x6d, 0x38, 0xd2, 0xca, 0xda, 0x50,
	0xca, 0x61, 0x08, 0xf7, 0x2d, 0x38, 0x18, 0x9f, 0xdd, 0x0f, 0x40, 0xfb, 0x4a, 0xc4, 0x46, 0x2a,
	0xc7, 0xd8, 0xd1, 0x64, 0xf6, 0xd8, 0x70, 0x33, 0xd6, 0xec, 0x2d, 0x42, 0x40, 0x29, 0xa9, 0x4e,
	0x7d, 0x19, 0xc0, 0x72, 0x65, 0xad, 0x72, 0xb7, 0xfd, 0xe0, 0xf6, 0xc6, 0x0b, 0xa4, 0x6e, 0x6c,
	0x23, 0x5b, 0x57, 0x06, 0xe0, 0x35, 0x20, 0xfd, 0x64, 0xd7, 0xc8, 0xac, 0x02, 0xae, 0x65, 0xb4,
	0x5c, 0x5d, 0xab, 0xdc, 0x6d, 0x78, 0xc9, 0x8a, 0x31, 0x52, 0xb7, 0x02, 0x6b, 0x6b, 0x95, 0xbb,
	0x33, 0x9e, 0xfd, 0xee, 0xbc, 0x41, 0x5a, 0x6f, 0xc3, 0xe4, 0x31, 0x0f, 0xc7, 0x70, 0xc4, 0x85,
	0x62, 0x94, 0xd4, 0x9e, 0xc0, 0xc4, 0xea, 0x6c, 0x78, 0xf8, 0xc9, 0xae, 0x92, 0x99, 0x0b, 0x24,
	0x27, 0xc2, 0xdc, 0xa2, 0xf3, 0x1a, 0x69, 0xbe, 0x0d, 0x93, 0x1e, 0x37, 0xfc, 0x7d, 0xb6, 0x31,
	0x52, 0x0f, 0xb8, 0xe1, 0x76, 0x57, 0xcb, 0xb3, 0xdf, 0x9d, 0x5b, 0xa4, 0xbe, 0x15, 0xca, 0x41,
	0x2e, 0xb2, 0x62, 0x89, 0x89, 0xc8, 0x0b, 0x42, 0x8f, 0x42, 0xee, 0xc3, 0xb9, 0x0c, 0x03, 0x50,
	0xd6, 0x24, 0x94, 0x6b, 0xf8, 0x30, 0x95, 0x6b, 0xf8, 0x90, 0xbd, 0x49, 0xea, 0x66, 0x12, 0x3b,
	0x6b, 0xda, 0x0f, 0x5e, 0x7e, 0x61, 0x54, 0x0a, 0x62, 0x4e, 0x26, 0x31, 0x78, 0x76, 0x07, 0x86,
	0xc5, 0x2a, 0xd2, 0xcb, 0xb5, 0xb5, 0xda, 0xdd, 0x96, 0x97, 0xac, 0x3a, 0xdf, 0x56, 0xd2, 0xbb,
	0xab, 0xe4, 0x38, 0x66, 0x7d, 0xd2, 0x8a, 0x73, 0x4c, 0x2f, 0x57, 0xd6, 0x6a, 0x77, 0x9b, 0x0f,
	0x3e, 0xf8, 0xdf, 0x69, 0xb3, 0x46, 0x7b, 0xa5, 0xad, 0x9d, 0x7b, 0x64, 0x6e, 0x33, 0x08, 0x14,
	0x68, 0xcd, 0xda, 0xa4, 0x2a, 0xe2, 0xc4, 0x99, 0xaa, 0x88, 0x31, 0x46, 0xb1, 0x54, 0xc6, 0xfa,
	0x52, 0xf3, 0xec, 0x77, 0xe7, 0xb3, 0x55, 0x32, 0xb7, 0xaf, 0x87, 0x5b, 0x5c, 0x03, 0xfb, 0x08,
	0x99, 0x1f, 0xe9, 0xe1, 0xa9, 0xf5, 0xd7, 0x65, 0xc1, 0xad, 0x17, 0x5a, 0xb0, 0xaf, 0x87, 0xd6,
	0xcf, 0xb9, 0x91, 0xfb, 0xc0, 0x00, 0x8f, 0xf4, 0xb0, 0xdf, 0x4b, 0x24, 0xbb, 0x05, 0xbb, 0x45,
	0x1a, 0x46, 0x8c, 0x40, 0x1b, 0x3e, 0x8a, 0x6d, 0x12, 0xd4, 0xbd, 0x1c, 0x60, 0x2b, 0x64, 0x5e,
	0xcb, 0xb1, 0xf2, 0xa1, 0xdf, 0x5b, 0xae, 0xdb, 0x6d, 0xd9, 0x1a, 0x69, 0x86, 0xab, 0x21, 0x98,
	0x7e, 0x6f, 0x79, 0xc6, 0xd1, 0xd2, 0x35, 0xdb, 0x23, 0x24, 0x56, 0x32, 0x06, 0x65, 0x04, 0xe8,
	0xe5, 0x59, 0x1b, 0xa8, 0x57, 0xde, 0xcf, 0x4c, 0x74, 0x6b, 0xe3, 0x28, 0x63, 0xdf, 0x8e, 0x8c,
	0x9a, 0x78, 0x85, 0xfd, 0x2b, 0x6f, 0x91, 0xc5, 0x29, 0xf2, 0xd7, 0x9a, 0x92, 0x1f, 0xad, 0xbe,
	0x59, 0xe9, 0xbc, 0x45, 0x1a, 0xfb, 0x7a, 0xf8, 0x10, 0x78, 0x00, 0x8a, 0x7d, 0x98, 0xd4, 0x07,
	0x5c, 0xbb, 0xd0, 0x35, 0xdf, 0x3f, 0x74, 0x68, 0x93, 0x67, 0x39, 0x3b, 0xdf, 0x4e, 0x5a, 0xbd,
	0xfd, 0xbd, 0xff, 0x85, 0x04, 0x8c, 0xb1, 0x3e, 0xe7, 0x2a, 0x38, 0xe0, 0xa3, 0xd4, 0xbc, 0x1c,
	0xe8, 0xbc, 0x57, 0x21, 0xad, 0x23, 0x25, 0x2e, 0x44, 0x08, 0x43, 0xd8, 0x7e, 0x66, 0xd8, 0x37,
	0x91, 0xa6, 0x1c, 0xbc, 0x03, 0xbe, 0x29, 0x1e, 0xf2, 0x9d, 0x17, 0xea, 0x39, 0xb4, 0x7c, 0xf6,
	0x9c, 0x89, 0xcc, 0xbe, 0xd9, 0x21, 0xa1, 0x89, 0x84, 0x38, 0x15, 0xfc, 0x5f, 0xde, 0x0d, 0x27,
	0x26, 0x33, 0xc2, 0x5b, 0x94, 0x65, 0x80, 0xad, 0x93, 0xcb, 0x89, 0xc0, 0x88, 0x8f, 0xe0, 0x54,
	0x44, 0x01, 0x3c, 0x4b, 0x4a, 0x46, 0xc2, 0x8b, 0xae, 0xf4, 0x11, 0x66, 0xaf, 0x10, 0xf6, 0x1c,
	0xaf, 0xb6, 0xd9, 0x33, 0xe3, 0xd1, 0x29, 0x66, 0xdd, 0xd9, 0x21, 0xad, 0x63, 0x18, 0x8e, 0x20,
	0x32, 0x58, 0xe7, 0x34, 0xc6, 0x2a, 0x59, 0xf7, 0x7b, 0xd6, 0xf5, 0x9a, 0x97, 0x03, 0x6c, 0x99,
	0xcc, 0x1d, 0x8c, 0x47, 0x9e, 0x7c, 0xaa, 0x93, 0x2c, 0x4e, 0x97, 0x9d, 0x1f, 0xa9, 0x12, 0xd2,
	0x0d, 0x05, 0xb2, 0x45, 0x67, 0x92, 0xdd, 0x20, 0xf3, 0x3a, 0x78, 0x92, 0x07, 0xb0, 0xe1, 0xcd,
	0xe9, 0xe0, 0x89, 0x0d, 0xce, 0x1d, 0xd2, 0x44, 0xd2, 0x05, 0x28, 0x2d, 0xb2, 0x72, 0x48, 0x74,
	0xf0, 0xe4, 0xb1, 0x43, 0xd8, 0x2a, 0x21, 0xa1, 0xf4, 0x79, 0x78, 0x8a, 0xf7, 0xc0, 0x7a, 0xd9,
	0xf0, 0x1a, 0x16, 0x39, 0x11, 0x23, 0xc0, 0x0b, 0x3a, 0xd6, 0xa0, 0xac, 0x47, 0x0d, 0xcf, 0x7e,
	0x23, 0x76, 0x2e, 0xb5, 0xb1, 0xf7, 0xa0, 0xe1, 0xd9, 0x6f, 0xd6, 0x27, 0xf3, 0x0a, 0x34, 0xa8,
	0x0b, 0x08, 0x92, 0x1b, 0x70, 0xef, 0x85, 0xc1, 0xcf, 0xad, 0xde, 0xf0, 0x12, 0x7e, 0x77, 0x05,
	0xb2, 0xed, 0x2b, 0xdf, 0x48, 0x16, 0x4a, 0xa4, 0xff, 0x51, 0xfa, 0x7f, 0xba, 0x4a, 0xc8, 0x31,
	0xee, 0x55, 0x36, 0x32, 0xab, 0x84, 0x0c, 0xc6, 0x22, 0x0c, 0x4e, 0x0d, 0x1f, 0xea, 0x44, 0x42,
	0xc3, 0x22, 0x27, 0x7c, 0xa8, 0x0b, 0x64, 0x91, 0x27, 0xab, 0x23, 0xa3, 0xf3, 0xab, 0x84, 0x0c,
	0x85, 0x39, 0x45, 0xd3, 0x85, 0x49, 0x63, 0x33, 0x14, 0xa6, 0x6b, 0x01, 0x4b, 0x96, 0x59, 0x68,
	0xeb, 0x09, 0x59, 0xa6, 0x91, 0xbd, 0x43, 0x9a, 0x01, 0xc4, 0xa1, 0x9c, 0x9c, 0x8e, 0xb0, 0xe7,
	0xb8, 0x68, 0x11, 0x07, 0xed, 0x63, 0x97, 0xfa, 0x5a, 0x63, 0x96, 0xfb, 0xf3, 0x7f, 0x12, 0xb3,
	0xf5, 0xcf, 0x11, 0xd2, 0xc8, 0xda, 0x28, 0x6b, 0x92, 0xb9, 0xe3, 0xb1, 0xef, 0x83, 0xd6, 0xf4,
	0x12, 0xbb, 0x42, 0x16, 0x1f, 0x45, 0xf0, 0x2c, 0x06, 0xdf, 0x40, 0x60, 0x79, 0x68, 0x85, 0x5d,
	0x26, 0x0b, 0x5d, 0x19, 0x45, 0xe0, 0x9b, 0x1d, 0x2e, 0x42, 0x08, 0x68, 0x95, 0x5d, 0x25, 0xf4,
	0x08, 0xd4, 0x48, 0x68, 0xf4, 0xbc, 0x07, 0x91, 0x80, 0x80, 0xd6, 0xd8, 0x75, 0x72, 0xa5, 0x2b,
	0xc3, 0x10, 0x7c, 0x23, 0x64, 0x74, 0x20, 0xcd, 0xf6, 0x33, 0xa1, 0x8d, 0xa6, 0x75, 0x14, 0xdb,
	0x0f, 0x43, 0x18, 0xf2, 0x70, 0x53, 0x0d, 0xc7, 0x98, 0xee, 0x74, 0x06, 0x65, 0x24, 0x60, 0x4f,
	0x8c, 0x20, 0x42, 0x49, 0x74, 0xae, 0x80, 0xda, 0x3b, 0x84, 0x49, 0x4d, 0xe7, 0xd9, 0x0d, 0xb2,
	0x94, 0xa0, 0x05, 0x05, 0x7c, 0x04, 0xb4, 0xc1, 0x16, 0x49, 0x33, 0x21, 0x9d, 0x1c, 0x1e, 0xbd,
	0x4d, 0x49, 0x41, 0x82, 0x27, 0x9f, 0x7a, 0xe0, 0x4b, 0x15, 0xd0, 0x66, 0xc1, 0x84, 0xc7, 0xe0,
	0x1b, 0xa9, 0xfa, 0x3d, 0xda, 0x42, 0x83, 0x13, 0xf0, 0x18, 0xb8, 0xf2, 0xcf, 0x3d, 0xd0, 0xe3,
	0xd0, 0xd0, 0x05, 0x46, 0x49, 0x6b, 0x47, 0x84, 0x70, 0x20, 0xcd, 0x8e, 0x1c, 0x47, 0x01, 0x6d,
	0xb3, 0x36, 0x21, 0xfb, 0x60, 0x78, 0x12, 0x81, 0x45, 0x54, 0xdb, 0xe5, 0xfe, 0x39, 0x24, 0x00,
	0x65, 0xd7, 0x08, 0xeb, 0xf2, 0x28, 0x92, 0xa6, 0xab, 0x80, 0x1b, 0xd8, 0xb1, 0xcd, 0x90, 0x5e,
	0x46, 0x73, 0x4a, 0xb8, 0x08, 0x81, 0xb2, 0x9c, 0xbb, 0x07, 0x21, 0x64, 0xdc, 0x57, 0x72, 0xee,
	0x04, 0x47, 0xee, 0xab, 0x68, 0xfc, 0x16, 0x66, 0xa9, 0x0d, 0x89, 0x3b, 0x96, 0x25, 0xb4, 0x31,
	0x31, 0xfe, 0x60, 0xaf, 0x7f, 0x7c, 0x42, 0xaf, 0xb1, 0x25, 0x72, 0x39, 0x41, 0xf6, 0xc1, 0x28,
	0xe1, 0xdb, 0xe0, 0x5d, 0x47, 0x53, 0x0f, 0xc7, 0xe6, 0xf0, 0x6c, 0x1f, 0x46, 0x52, 0x4d, 0xe8,
	0x32, 0x1e, 0xa8, 0x95, 0x94, 0x1e, 0x11, 0xbd, 0x81, 0x1a, 0xb6, 0x47, 0xb1, 0x99, 0xe4, 0xe1,
	0xa5, 0x2b, 0xec, 0x26, 0xb9, 0xfe, 0x28, 0x0e, 0xb8, 0x81, 0xfe, 0x08, 0x3b, 0xf5, 0x09, 0xd7,
	0x4f, 0xd0, 0xdd, 0xb1, 0x02, 0x7a, 0x93, 0xad, 0x90, 0x6b, 0xe5, 0xb3, 0xc8, 0x82, 0x75, 0x0b,
	0x37, 0x3a, 0x6f, 0xbb, 0x0a, 0x02, 0x88, 0x8c, 0xe0, 0x61, 0xba, 0x71, 0x35, 0x97, 0xfa, 0x3c,
	0xf1, 0x36, 0x12, 0x9d, 0xe7, 0xcf, 0x13, 0xef, 0xb0, 0x65, 0x72, 0x75, 0x17, 0xcc, 0xf3, 0x94,
	0x35, 0xa4, 0xec, 0x09, 0x6d, 0x49, 0x8f, 0x34, 0x28, 0x9d, 0x52, 0x5e, 0x62, 0x8c, 0xb4, 0x77,
	0xc1, 0x20, 0x98, 0x62, 0x1d, 0x8c, 0x93, 0x33, 0xcf, 0x93, 0x21, 0xa4, 0xf0, 0x07, 0x30, 0x06,
	0x3d, 0x25, 0xe3, 0x22, 0xf8, 0x32, 0xba, 0x79, 0x18, 0x83, 0xe2, 0x06, 0x50, 0x46, 0x91, 0xf6,
	0x41, 0x94, 0x73, 0x0c, 0x18, 0x81, 0x22, 0xfc, 0xa1, 0x1c, 0x2e, 0x6a, 0xfd, 0x7f, 0x98, 0xc3,
	0x09, 0x37, 0xb8, 0x31, 0x23, 0x25, 0xdd, 0x45, 0xaf, 0x13, 0x25, 0x59, 0x57, 0x4a, 0x89, 0xff,
	0x1f, 0x53, 0xc5, 0xed, 0xdb, 0x55, 0x3c, 0x32, 0x29, 0xbe, 0xce, 0x5e, 0x22, 0xab, 0x1e, 0x9c,
	0x29, 0xd0, 0xe7, 0x47, 0x32, 0x14, 0xfe, 0x04, 0x0b, 0x46, 0x96, 0x92, 0xc8, 0xf2, 0x75, 0x68,
	0x09, 0x86, 0xc5, 0xd1, 0x53, 0xf8, 0x15, 0x8c, 0xc9, 0x81, 0x34, 0xc7, 0xd8, 0xa4, 0xf7, 0x6c,
	0xdb, 0xa7, 0xf7, 0x50, 0xcb, 0x81, 0xf4, 0x20, 0x0e, 0x85, 0xcf, 0x37, 0x2f, 0xb8, 0x08, 0xf9,
	0x20, 0x04, 0xba, 0x81, 0x41, 0x49, 0x3a, 0x54, 0x76, 0xbe, 0xf7, 0xd9, 0x02, 0x69, 0xec, 0x48,
	0xe5, 0x43, 0x0f, 0xa2, 0x09, 0xfd, 0x30, 0x2e, 0x3d, 0x6e, 0x60, 0x4f, 0x8c, 0x84, 0xa1, 0xaf,
	0x3a, 0xf1, 0x01, 0xf4, 0x7b, 0x07, 0xd2, 0xec, 0x73, 0xe3, 0x9f, 0xd3, 0x07, 0x98, 0xd7, 0x8f,
	0x62, 0x0d, 0xca, 0x6c, 0x8e, 0x8d, 0xec, 0xf7, 0x4e, 0xd4, 0x18, 0xe8, 0x6b, 0xec, 0x16, 0x59,
	0xee, 0x47, 0x7a, 0x7c, 0x76, 0x26, 0x7c, 0x6c, 0x13, 0x2e, 0x41, 0x4f, 0xe4, 0x9e, 0xe4, 0x01,
	0x7d, 0x1d, 0x0f, 0xd5, 0x21, 0x1f, 0x1b, 0x4b, 0xc3, 0xb7, 0x9f, 0x9d, 0xf3, 0xb1, 0x36, 0x10,
	0xd0, 0xaf, 0x47, 0x63, 0x7b, 0x42, 0x3f, 0x99, 0xc2, 0xdf, 0x40, 0x7f, 0xb1, 0x90, 0x9f, 0x08,
	0xff, 0xc9, 0x9e, 0x8c, 0x86, 0x3d, 0x08, 0xf9, 0x84, 0x7e, 0x04, 0xf3, 0xfd, 0x40, 0x1a, 0x0f,
	0x78, 0x30, 0xb1, 0xb5, 0x95, 0xbe, 0x89, 0x11, 0x4f, 0xa1, 0xae, 0x94, 0x2a, 0xd8, 0xf4, 0x8d,
	0xb8, 0xe0, 0x46, 0x44, 0x43, 0xfa, 0x0d, 0x78, 0x61, 0x70, 0xce, 0xb7, 0x84, 0x83, 0x4d, 0x1a,
	0x30, 0x46, 0x16, 0x7a, 0x3d, 0x0f, 0x3e, 0x3e, 0x06, 0x6d, 0x3c, 0xee, 0x03, 0xfd, 0xc7, 0xb9,
	0x75, 0x9f, 0x10, 0x7b, 0x89, 0xb0, 0xb3, 0x63, 0xdf, 0x6c, 0xe7, 0xab, 0x03, 0x19, 0x01, 0xbd,
	0xc4, 0x5a, 0x64, 0xfe, 0x51, 0x24, 0xb4, 0x1e, 0x43, 0x40, 0x2b, 0x58, 0x40, 0xfa, 0xd1, 0x91,
	0x92, 0x43, 0x1c, 0x8c, 0x69, 0x15, 0xa9, 0x3b, 0x22, 0x12, 0xfa, 0xdc, 0x96, 0x4e, 0x42, 0x66,
	0x93, 0x4a, 0x52, 0x67, 0x0d, 0x32, 0xe3, 0x81, 0x51, 0x13, 0x3a, 0xb3, 0xfe, 0x6e, 0xa5, 0x34,
	0x41, 0xe0, 0x9c, 0x4b, 0x8b, 0xeb, 0x5c, 0x53, 0x76, 0x97, 0x2b, 0x58, 0xd1, 0x77, 0x95, 0x7c,
	0x8a, 0xbe, 0x54, 0x51, 0xf0, 0x31, 0xf0, 0xd0, 0x2a, 0x69, 0x92, 0xb9, 0x9d, 0x70, 0x6c, 0x35,
	0xd6, 0xad, 0x7e, 0x5c, 0x20, 0xdb, 0x0c, 0x92, 0x30, 0xf7, 0x63, 0x08, 0xe8, 0x2c, 0x9e, 0xa7,
	0xbb, 0xf1, 0x48, 0x9b, 0x5b, 0x17, 0x64, 0x71, 0xea, 0x7d, 0xc1, 0xe6, 0x49, 0x3d, 0x51, 0x4d,
	0x49, 0x6b, 0x4b, 0x44, 0x5c, 0x4d, 0x5c, 0x59, 0xa5, 0x01, 0x46, 0x6f, 0x27, 0x94, 0xdc, 0x24,
	0x00, 0x60, 0xf8, 0x2d, 0xf0, 0xea, 0x1b, 0x09, 0x74, 0x86, 0x2e, 0xf6, 0x23, 0xf3, 0xc6, 0xeb,
	0x4e, 0xf3, 0x63, 0xae, 0xba, 0xe7, 0x5c, 0xd1, 0xa5, 0xf5, 0xcf, 0x50, 0xfb, 0x16, 0xb0, 0x3a,
	0x16, 0x48, 0xe3, 0x51, 0x14, 0xc0, 0x99, 0x88, 0x20, 0xa0, 0x97, 0x6c, 0x65, 0x74, 0x35, 0x25,
	0x2f, 0x51, 0x78, 0x32, 0x6d, 0xb4, 0xbb, 0x80, 0x59, 0x7d, 0x0f, 0xb9, 0x2e, 0x40, 0x67, 0x36,
	0x61, 0xec, 0xeb, 0x73, 0x50, 0xdc, 0x3e, 0xb4, 0xd9, 0x7d, 0x2e, 0x9f, 0xe6, 0x98, 0xa6, 0xe7,
	0xa8, 0x69, 0x17, 0xcc, 0xf1, 0x44, 0x1b, 0x18, 0x75, 0x65, 0x74, 0x26, 0x86, 0x9a, 0x0a, 0xd4,
	0x84, 0x79, 0x59, 0xd8, 0xfe, 0x0e, 0xe6, 0x9b, 0x07, 0x21, 0x70, 0x5d, 0x94, 0xfa, 0xc4, 0xf6,
	0x06, 0x6b, 0xea, 0x66, 0x28, 0xb8, 0xa6, 0x21, 0xba, 0x82, 0x56, 0xba, 0xe5, 0x08, 0x53, 0x61,
	0x33, 0x34, 0xa0, 0xdc, 0x3a, 0x42, 0x2b, 0xec, 0xba, 0x20, 0x44, 0xa2, 0x15, 0x1e, 0xe0, 0x90,
	0x59, 0x40, 0x63, 0xf4, 0x2d, 0x75, 0xc4, 0xed, 0xfe, 0x38, 0x6a, 0xc3, 0x4b, 0x6e, 0x97, 0xa0,
	0xa9, 0x62, 0x57, 0xc9, 0xa2, 0x53, 0x7f, 0xc4, 0x95, 0x11, 0x76, 0xe3, 0xe7, 0x2b, 0x36, 0x87,
	0x95, 0x8c, 0x73, 0xec, 0x0b, 0xd8, 0xd9, 0x5b, 0x0f, 0xb9, 0xce, 0xa1, 0x3f, 0xae, 0xb0, 0x6b,
	0xe4, 0x72, 0xaa, 0x20, 0xc7, 0xff, 0xa4, 0xc2, 0xae, 0x90, 0x36, 0x46, 0x2a, 0xc3, 0x34, 0xfd,
	0x53, 0x0b, 0x62, 0x4c, 0x0a, 0xe0, 0x9f, 0x59, 0x09, 0x49, 0x50, 0x0a, 0xf8, 0x9f, 0x5b, 0x65,
	0x28, 0x21, 0x49, 0x5f, 0x4d, 0xbf, 0x58, 0x41, 0x4b, 0x53, 0x65, 0x09, 0x4c, 0xdf, 0xb3, 0x8c,
	0x28, 0x35, 0x63, 0xfc, 0x92, 0x65, 0x4c, 0x64, 0x66, 0xe8, 0x97, 0x2d, 0xfa, 0x90, 0x47, 0x81,
	0x3c, 0x3b, 0xcb, 0xd0, 0xaf, 0x54, 0xd8, 0x32, 0xb9, 0x82, 0xdb, 0xb7, 0x78, 0xc8, 0x23, 0x3f,
	0xe7, 0xff, 0x6a, 0x85, 0x2d, 0x11, 0x3a, 0xa5, 0x4e, 0xd3, 0x4f, 0x56, 0xd9, 0x2d, 0x72, 0x7d,
	0x07, 0x02, 0x50, 0x18, 0x45, 0x7b, 0x89, 0x21, 0xd5, 0x4d, 0x3f, 0x55, 0x65, 0x1d, 0xb2, 0x6a,
	0xa9, 0x53, 0x3b, 0x2d, 0x23, 0x56, 0x09, 0xfa, 0x6e, 0x95, 0xd1, 0xf4, 0xc0, 0x2d, 0x4a, 0x7f,
	0xbe, 0x6a, 0xa3, 0x9d, 0x6c, 0x70, 0xd8, 0x2f, 0x54, 0x59, 0xdb, 0x65, 0x81, 0x5b, 0xff, 0x62,
	0x95, 0x5d, 0x27, 0x6c, 0x17, 0x4c, 0x56, 0x36, 0x84, 0x36, 0xc2, 0xd7, 0xf4, 0x97, 0xaa, 0xac,
	0x49, 0x66, 0xfb, 0x11, 0x16, 0x4b, 0xfa, 0xfd, 0x78, 0x69, 0x67, 0x5d, 0x47, 0xa4, 0x3f, 0x80,
	0x65, 0x62, 0xc6, 0x5e, 0x5a, 0xfa, 0x83, 0x38, 0x6d, 0x31, 0x9c, 0x01, 0xa3, 0xa0, 0xf8, 0xc4,
	0xa0, 0x3f, 0x64, 0x77, 0xb8, 0x5a, 0x4b, 0x7f, 0xd8, 0x2e, 0xdc, 0x6c, 0x43, 0xff, 0xb9, 0x66,
	0x8f, 0xa0, 0x38, 0xe8, 0xfc, 0x4b, 0x0d, 0x0d, 0x2d, 0x1a, 0x01, 0xf4, 0x5f, 0x6b, 0x6c, 0x85,
	0x2c, 0xa5, 0x98, 0x1d, 0x3b, 0xb2, 0xaa, 0xf5, 0x6f, 0x35, 0x0c, 0x16, 0xf6, 0xe0, 0x2c, 0x27,
	0x0b, 0x96, 0xff, 0x7b, 0x8d, 0xdd, 0x24, 0xd7, 0x76, 0xc1, 0x64, 0xe7, 0x5e, 0x20, 0xfe, 0x47,
	0x8d, 0x2d, 0x90, 0x79, 0xac, 0x6b, 0x02, 0x2e, 0x80, 0x7e, 0xb1, 0x86, 0xc9, 0x93, 0x2e, 0x13,
	0x73, 0xde, 0xab, 0xe1, 0x91, 0x7e, 0x33, 0xb6, 0x8c, 0xde, 0xa8, 0x7b, 0xce, 0xa3, 0x08, 0x42,
	0x4d, 0xbf, 0x54, 0xc3, 0x83, 0xf3, 0x60, 0x24, 0x2f, 0xa0, 0x00, 0x7f, 0xd9, 0x46, 0xc0, 0x32,
	0x7f, 0x6c, 0x0c, 0x6a, 0x92, 0x11, 0xbe, 0x52, 0xc3, 0x14, 0x70, 0xfc, 0x65, 0xca, 0x57, 0x6b,
	0x6c, 0x95, 0x2c, 0xbb, 0x72, 0x98, 0x26, 0x00, 0x12, 0x87, 0x80, 0xbd, 0x93, 0x7e, 0xb2, 0x9e,
	0x49, 0xec, 0x41, 0x68, 0x78, 0xb6, 0xef, 0x53, 0x75, 0xb4, 0x0b, 0x6b, 0x42, 0xde, 0x32, 0x35,
	0x7d, 0xb7, 0x8e, 0xe7, 0xbe, 0x0b, 0x26, 0xe9, 0x9a, 0x9a, 0x7e, 0x07, 0x4e, 0xba, 0xed, 0x47,
	0x91, 0x1e, 0x0f, 0x32, 0x43, 0xe9, 0x77, 0xa6, 0x9b, 0x7b, 0x42, 0x1b, 0x25, 0x06, 0x63, 0x7b,
	0xa3, 0xbe, 0xab, 0x8e, 0x4e, 0x1d, 0x4f, 0x22, 0xbf, 0x04, 0x7f, 0xb7, 0x95, 0x99, 0xa5, 0xd8,
	0x99, 0xa4, 0x7f, 0x51, 0x67, 0x8b, 0x84, 0xb8, 0x62, 0x64, 0x81, 0xbf, 0x4c, 0xe5, 0xe1, 0x68,
	0x7b, 0x01, 0xca, 0xf6, 0x7d, 0xfa, 0x57, 0x99, 0x89, 0x85, 0xee, 0x40, 0xff, 0xba, 0x8e, 0x41,
	0x4f, 0x5b, 0x22, 0xfd, 0xe5, 0x06, 0xda, 0x67, 0x63, 0x82, 0x0d, 0xda, 0x25, 0xcc, 0xa7, 0x1b,
	0x98, 0x98, 0x78, 0x63, 0x5c, 0x62, 0xfe, 0x8a, 0x5d, 0x27, 0xcd, 0xae, 0xdf, 0xa3, 0xbf, 0x8a,
	0x23, 0x36, 0x49, 0xd6, 0x27, 0xc7, 0x87, 0xf4, 0x33, 0x0d, 0x54, 0xb5, 0x19, 0xe2, 0xa3, 0xd1,
	0x64, 0xf7, 0xf6, 0xd7, 0x1a, 0x78, 0xf1, 0x0b, 0xda, 0x93, 0x73, 0xff, 0xf5, 0x86, 0x75, 0xd4,
	0xe1, 0x36, 0x77, 0x7b, 0xd8, 0x38, 0x7e, 0xc3, 0x4a, 0xc5, 0xfb, 0x83, 0x96, 0x9c, 0x18, 0xfa,
	0x9b, 0x0d, 0xd6, 0x22, 0x73, 0xc9, 0x3b, 0x83, 0xfe, 0x96, 0xd5, 0x61, 0x47, 0xba, 0xec, 0x01,
	0xa9, 0xe9, 0x6f, 0x5b, 0xfb, 0xad, 0xe6, 0x93, 0xf4, 0x57, 0x1c, 0xfa, 0x59, 0xab, 0x60, 0x7a,
	0xdc, 0xa4, 0x7f, 0xd3, 0x4c, 0x52, 0xbb, 0x80, 0xfd, 0x6d, 0xd3, 0x95, 0x80, 0xf2, 0x7c, 0x49,
	0xff, 0xce, 0xc2, 0xd3, 0x33, 0x29, 0xfd, 0xfb, 0x26, 0x7a, 0x54, 0x1c, 0x2b, 0xb1, 0x1a, 0x6b,
	0xfa, 0x0f, 0x4d, 0x34, 0x3d, 0x1f, 0x20, 0xe9, 0xef, 0xb4, 0x30, 0xca, 0xe9, 0xe8, 0x48, 0x7f,
	0xb7, 0x85, 0xb6, 0x4f, 0x0d, 0x8d, 0xf4, 0xf7, 0x5a, 0xf6, 0x1c, 0xb3, 0x71, 0x91, 0x7e, 0xae,
	0x00, 0x20, 0x17, 0xfd, 0xfd, 0x96, 0x2d, 0xb2, 0xa5, 0x11, 0x91, 0xfe, 0x41, 0x0b, 0x6d, 0x9b,
	0x1e, 0x0e, 0xe9, 0x1f, 0xb6, 0x5c, 0x9e, 0x64, 0x63, 0x21, 0xfd, 0xa3, 0x16, 0x5e, 0xbe, 0x17,
	0x0f, 0x84, 0xf4, 0xf3, 0x56, 0x57, 0x3e, 0x0a, 0xd2, 0x2f, 0xb4, 0xf0, 0x8e, 0x24, 0x3e, 0x24,
	0xba, 0xec, 0xef, 0x80, 0xf4, 0x27, 0x16, 0x6c, 0x0b, 0x40, 0x67, 0x4a, 0xf8, 0x4f, 0x2e, 0xe0,
	0xe5, 0x40, 0x11, 0x25, 0x5c, 0xd3, 0x9f, 0x5a, 0xc0, 0x7a, 0x91, 0x16, 0xbb, 0xf2, 0xa6, 0x9f,
	0x5e, 0xc0, 0x92, 0x73, 0xa2, 0x78, 0xa4, 0xcf, 0x40, 0xe1, 0x49, 0xd3, 0x9f, 0x59, 0xc0, 0xe8,
	0xa4, 0x50, 0x72, 0x75, 0xe8, 0xcf, 0x2e, 0xa0, 0xef, 0xce, 0x1e, 0x4c, 0x8a, 0x01, 0xd7, 0x40,
	0xbf, 0xa7, 0x8d, 0xbb, 0xd1, 0x94, 0x0c, 0xfa, 0xde, 0x36, 0x9e, 0x2a, 0x5a, 0x91, 0x42, 0x9a,
	0x7e, 0x5f, 0x7b, 0xbd, 0x43, 0xe6, 0x7a, 0x3a, 0xb4, 0x53, 0xc3, 0x1c, 0xa9, 0xf5, 0x74, 0x48,
	0x2f, 0x61, 0x93, 0xdd, 0x92, 0x32, 0xdc, 0x7e, 0x16, 0xab, 0xc7, 0xaf, 0xd2, 0xca, 0xfa, 0x16,
	0x59, 0xec, 0xca, 0x51, 0xcc, 0xb3, 0xaa, 0x65, 0x07, 0x05, 0x37, 0x61, 0x40, 0xe0, 0xee, 0xcb,
	0x25, 0xec, 0xd4, 0xdb, 0xcf, 0xc0, 0x1f, 0xdb, 0xd1, 0xa7, 0x82, 0x4b, 0xdc, 0x84, 0x09, 0x13,
	0xd0, 0xea, 0xfa, 0xb7, 0x10, 0xda, 0x95, 0x91, 0x16, 0xda, 0x40, 0xe4, 0x4f, 0xf6, 0xe0, 0x02,
	0x42, 0x3b, 0x60, 0x19, 0x25, 0xa3, 0x21, 0xbd, 0x64, 0xdf, 0xd2, 0x60, 0xdf, 0xc4, 0x6e, 0x0c,
	0xdb, 0xc2, 0x79, 0xd9, 0x3e, 0x98, 0xdb, 0x84, 0x6c, 0x5f, 0x40, 0x64, 0xc6, 0x3c, 0x0c, 0x27,
	0xb4, 0x86, 0xeb, 0xee, 0x58, 0x1b, 0x39, 0x12, 0x9f, 0xc0, 0x69, 0x6c, 0xfd, 0x47, 0x2b, 0xa4,
	0xe9, 0x66, 0xae, 0xcc, 0x34, 0xb7, 0x3c, 0x82, 0x28, 0x10, 0x56, 0x38, 0xbe, 0xf7, 0x2c, 0x94,
	0x0c, 0x8a, 0x95, 0x9c, 0xe9, 0xd8, 0x70, 0x65, 0x2d, 0xb4, 0xcf, 0xdc, 0x64, 0x9f, 0xb2, 0x76,
	0x06, 0x74, 0x26, 0xe7, 0x4b, 0xa7, 0xbf, 0xf9, 0x9c, 0x2f, 0x77, 0x6f, 0x16, 0xdf, 0x3a, 0x45,
	0x0d, 0x9b, 0x51, 0xd0, 0x0d, 0x81, 0xe3, 0xf8, 0x35, 0xb7, 0xfe, 0x80, 0x90, 0xfc, 0xf7, 0x38,
	0x6b, 0x7e, 0x3e, 0x96, 0x5c, 0xc2, 0x20, 0xec, 0x86, 0x72, 0xc0, 0x43, 0x5a, 0xc1, 0xd9, 0xd0,
	0xe6, 0x73, 0x75, 0xfd, 0xc7, 0xe7, 0xc9, 0xe2, 0xd4, 0xaf, 0x6f, 0xe8, 0x45, 0xb6, 0xd8, 0x0c,
	0xf1, 0xa0, 0x56, 0xc9, 0x8d, 0x0c, 0x79, 0x6e, 0xc2, 0xab, 0xe0, 0xa4, 0x9e, 0x91, 0xa7, 0x46,
	0xbd, 0x2a, 0xbb, 0x43, 0x6e, 0xe6, 0xc4, 0xe7, 0x07, 0x3c, 0x6c, 0x57, 0xcb, 0x19, 0xc3, 0xf4,
	0xa4, 0x57, 0xc7, 0xc0, 0x64, 0x54, 0xfb, 0xe8, 0xb0, 0xbf, 0x4a, 0xe4, 0x3f, 0x15, 0xba, 0x91,
	0x83, 0xce, 0xb2, 0xeb, 0xe4, 0x4a, 0x6e, 0x63, 0x96, 0x45, 0x74, 0x0e, 0xe3, 0x98, 0x11, 0x92,
	0x9e, 0x3d, 0x5f, 0x02, 0x93, 0xde, 0xdd, 0xc0, 0xe0, 0x66, 0x20, 0xd6, 0xe9, 0xbc, 0x44, 0x12,
	0x7c, 0xe9, 0x4c, 0x85, 0xc0, 0xd5, 0xe2, 0x66, 0x89, 0xe2, 0x46, 0x0e, 0x30, 0x5c, 0x84, 0xb4,
	0x85, 0x23, 0x6d, 0x29, 0x2e, 0x6e, 0xc7, 0x42, 0x49, 0x79, 0xd2, 0xf9, 0xf1, 0xd2, 0xb4, 0xf3,
	0x97, 0xa5, 0x1d, 0x20, 0x16, 0x4b, 0x98, 0xed, 0x09, 0x94, 0x96, 0xd4, 0x15, 0x86, 0x28, 0x7a,
	0xb9, 0xec, 0xa8, 0x4d, 0x12, 0xca, 0x4a, 0xd1, 0x75, 0x76, 0x1f, 0x3e, 0x8d, 0x40, 0xe9, 0x73,
	0x11, 0xd3, 0x2b, 0xa5, 0xa0, 0xb9, 0xea, 0x6a, 0xf3, 0xe2, 0x6a, 0x29, 0x14, 0x68, 0x7a, 0xbe,
	0x69, 0xa9, 0x7c, 0x60, 0xb6, 0xbe, 0xe5, 0xd4, 0x6b, 0x25, 0xea, 0x3e, 0x8f, 0xf8, 0xb0, 0xa0,
	0xf0, 0x7a, 0x49, 0x61, 0xa1, 0xb0, 0x2e, 0x97, 0x8c, 0x4f, 0x46, 0xa3, 0x1b, 0x6c, 0x8d, 0xdc,
	0x9a, 0x32, 0xbe, 0x5c, 0xbc, 0x56, 0xd8, 0x6d, 0xb2, 0x52, 0xb2, 0xb3, 0x4c, 0xbf, 0xc9, 0x3a,
	0xe4, 0xf6, 0x73, 0xd9, 0x57, 0xe6, 0xb9, 0x55, 0xca, 0xd0, 0x17, 0x54, 0xcf, 0x55, 0x76, 0x83,
	0x2c, 0x65, 0x0c, 0xa5, 0x4a, 0x79, 0xbb, 0xe4, 0xed, 0x74, 0xc5, 0xbc, 0x53, 0x92, 0xbc, 0x0b,
	0x06, 0x8f, 0x4b, 0x44, 0xc3, 0x6c, 0x56, 0x5b, 0x2b, 0x49, 0x4e, 0x18, 0x5c, 0x99, 0x7b, 0xa9,
	0x74, 0xe7, 0x9e, 0x7b, 0x65, 0x74, 0x4a, 0x77, 0x6e, 0xaa, 0x28, 0x7f, 0xa0, 0x24, 0xb6, 0x54,
	0x9c, 0x5f, 0x2e, 0x1d, 0x6c, 0xb9, 0x48, 0xdb, 0x1f, 0x4b, 0xca, 0x29, 0x88, 0xb7, 0xff, 0x43,
	0xeb, 0xc7, 0xa4, 0x61, 0x8d, 0xb2, 0xbf, 0x45, 0x62, 0x89, 0x8b, 0x04, 0x76, 0x5f, 0xf1, 0x09,
	0x91, 0x56, 0xd4, 0x87, 0xc0, 0x43, 0x73, 0x3e, 0xa1, 0x15, 0x7c, 0xb2, 0x6e, 0x0e, 0x22, 0xa9,
	0x46, 0x3c, 0xa4, 0x55, 0x5b, 0x6c, 0x0d, 0x8f, 0x82, 0x2d, 0xac, 0xa7, 0x2d, 0x32, 0x7f, 0x6c,
	0x64, 0x1c, 0xe3, 0xae, 0xfa, 0xba, 0xef, 0x06, 0x1a, 0x57, 0x4a, 0x97, 0xc8, 0xe5, 0x6c, 0x91,
	0xbd, 0x92, 0xed, 0x7b, 0xb2, 0x08, 0xdb, 0xeb, 0x5f, 0x29, 0xa1, 0x49, 0x44, 0x5d, 0x55, 0x2d,
	0xa1, 0xf8, 0x9a, 0xfe, 0xa8, 0x24, 0x97, 0xb3, 0x3f, 0x20, 0x4e, 0xe1, 0x99, 0x39, 0x95, 0x83,
	0x77, 0xd8, 0x9d, 0x0d, 0xf7, 0xaf, 0xe7, 0x46, 0xfa, 0xaf, 0xe7, 0xc6, 0x3e, 0x68, 0x8d, 0x79,
	0x1a, 0xdb, 0xa2, 0xb3, 0xfc, 0x4f, 0x73, 0xf6, 0x9f, 0x95, 0x97, 0x5e, 0xfc, 0xc7, 0x5a, 0xe1,
	0x9f, 0x12, 0x6f, 0x31, 0x2e, 0xac, 0x0e, 0x07, 0xef, 0x6c, 0x8d, 0x48, 0x5b, 0xc8, 0x74, 0xdf,
	0x50, 0xc5, 0xfe, 0x56, 0xb3, 0x6b, 0xf7, 0x1d, 0xa1, 0x8c, 0xa3, 0xca, 0xb7, 0xbe, 0x3e, 0x14,
	0xe6, 0x7c, 0x3c, 0x40, 0x69, 0xf7, 0x1d, 0xdb, 0x3d, 0x21, 0xd3, 0x2f, 0xab, 0xe8, 0xfe, 0x50,
	0xde, 0xe3, 0xb1, 0xb8, 0x7f, 0xf1, 0xe0, 0xbe, 0x53, 0x19, 0x0f, 0x7e, 0xac, 0x52, 0xf9, 0xb9,
	0x2a, 0xdb, 0x77, 0x52, 0xdd, 0xb4, 0xb5, 0xb1, 0xab, 0x62, 0x7f, 0x30, 0x6b, 0x77, 0xbc, 0xf6,
	0x9f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xd5, 0x1e, 0xe1, 0x67, 0xeb, 0x1d, 0x00, 0x00,
}
